brainboxdotcc/DPP

- README.md
> fixing hyperlinks redirecting to the wrong page

- include/dpp/user.h
- src/dpp/user.cpp
This pull requests adds the new certified moderator user flag.
PR in discord-api-docs: discord/discord-api-docs#2946
> Add certified moderator badge

- docpages/02_build.md
This pull request just enhances the current documentation to explain how to configure a CMake project.
> Added documentation for CMake

- include/dpp/cluster.h
- include/dpp/message.h
- src/dpp/cluster.cpp
- src/dpp/message.cpp
Changes "v8/applications" to "v9/applications" too.
Overload set_author to allow author object being passed
> Get webhook messages + document footer methods + minor improvements

- include/dpp/discord.h
- include/dpp/emoji.h
- src/dpp/cluster.cpp
- src/dpp/emoji.cpp
- src/dpp/managed.cpp
I know it's not cool to have feature and a fix at the same time. The fix is important, but the "features" are just a shortcut I think are great for some applications.
The important one is the `src/dpp/cluster.cpp`
> Emoji shortcuts and important fix for segmentation fault!

- include/dpp/cluster.h
- include/dpp/dispatcher.h
- include/dpp/event.h
- include/dpp/message.h
- makerelease.sh
- src/dpp/cluster.cpp
- src/dpp/discordevents.cpp
- src/dpp/dispatcher.cpp
- src/dpp/events/guild_stickers_update.cpp
- src/dpp/message.cpp
Better (read as: full) support for stickers via REST calls for their creation and editing, plus sticker change events.
> sticker REST and events support

- src/dpp/slashcommand.cpp
If you try something like guild_commands_get, it would only load the ids, but sometimes it is useful to know their names and description.
> Added some features missing (slashcommands)

- docpages/03_example_programs.md
Added documentation for subcommands in slash commands.
> Subcommand documentations.

- README.md
- docpages/02_build.md
- docpages/INDEX.md
- include/dpp/discordvoiceclient.h
- src/dpp/sslclient.cpp
- Fix header inclusion order in some files for compiling on FreeBSD
- Document FreeBSD build
> FreeBSD Support

- src/dpp/commandhandler.cpp
> Switch case `break;` in `commandhandler.cpp`

- src/dpp/discordvoiceclient.cpp
- src/test.cpp
some stuff to merge back to master to get them in sync
> voice test case

- docpages/03_example_programs.md
Example program for streaming ogg opus file
> docs: ogg opus example

- .dockerignore
- CMakeLists.txt
- Dockerfile
It would be great if you can add this base image to Docker Hub
> build: add Dockerfile

- include/dpp/role.h
- src/dpp/role.cpp
Adds `unicode_emoji` and `icon` properties to the Role class.
> Add support for role icons

- docpages/03_example_programs.md
Example for recording some user in a VC
> docs: voice receive example

- include/dpp/cluster.h
- include/dpp/dispatcher.h
- src/dpp/cluster.cpp
- src/dpp/discordvoiceclient.cpp
- src/dpp/dispatcher.cpp
- Client Speaking Event
- Client Disconnect Event
> feat: voice events

- src/dpp/auditlog.cpp
- src/dpp/ban.cpp
- src/dpp/cluster.cpp
- src/dpp/commandhandler.cpp
- src/dpp/discordvoiceclient.cpp
- src/dpp/dtemplate.cpp
- src/dpp/httplib.cpp
- src/dpp/invite.cpp
- src/dpp/message.cpp
- src/dpp/presence.cpp
- src/dpp/queues.cpp
- src/dpp/voiceregion.cpp
- src/dpp/voicestate.cpp
@braindigitalis review code please
> fix: code refactor

- src/dpp/discordvoiceclient.cpp
- Check whether voice_client_speaking event is attached before trying to call it
> fix: check if voice_client_speaking is attached

- include/dpp/commandhandler.h
Updated forward declarations in commandhandler.h to get rid of a couple of warnings
> Fixed a couple of small warnings in commandhandler.h

- docpages/style.css
- include/dpp/slashcommand.h
- src/dpp/slashcommand.cpp
Adds support for https://github.com/discord/discord-api-docs/discussions/3327
> Slash Commands Integer Option max and min

- include/dpp/channel.h
- include/dpp/guild.h
- src/dpp/channel.cpp
- src/dpp/guild.cpp
Add support for storing channel icon and banner, [Discord PR 4068](https://github.com/discord/discord-api-docs/pull/4068)
> add channel icon and banner, discord docs PR#4068

- README.md
Changed MinGW to mingw-w64 in README.md and added link to official website.
> Fixed mingw, added link

- include/dpp/slashcommand.h
- src/dpp/slashcommand.cpp
added messages as it was missing for the context menus
**(idk if it'll work )![grafik](https://user-images.githubusercontent.com/44061123/145689747-a3f83490-d1d3-4366-b2ce-c75a75ba81cd.png)**
> added messages to slashcommands

- docpages/03_example_programs.md
the code in the example was not displayed correctly
> small fix for the code in the context menu example

- include/dpp/guild.h
- src/dpp/guild.cpp
https://discord.com/developers/docs/reference#image-formatting
> added icon, banner, splash and discovery splash -url getters

- include/dpp/presence.h
updated presences activity types ~~not including custom since bots cant access the emoji field to use it correctly.~~
https://discord.com/developers/docs/topics/gateway#activity-object-activity-types
> Update presence.h activity types to match whats on the discord docs.

- include/dpp/discord.h
I noticed that "current" was "urrent" there. Small fix ;P
> Small issue with current_date_time description

- include/dpp/cluster.h
discord suggestion https://discord.com/channels/825407338755653642/825411707521728512/928998689962336267
> added note to user_get

- include/dpp/appcommand.h
- include/dpp/cache.h
- include/dpp/guild.h
added note to `guild_member::get_avatar_url`
> little docs changes

- include/dpp/cluster.h
- include/dpp/invite.h
- src/dpp/cluster/invite.cpp
- src/dpp/invite.cpp
- fixed a bug where `invite.guild_id` is not set, because the json was wrong parsed
- added some attributes to `invite`
- docs
> improvements in invite class & docs enhancements

- docpages/03_example_programs.md
discord conversation about that: https://discord.com/channels/825407338755653642/825411707521728512/932168845412667434
> added note to slash command example in the docs

- .gitignore
- include/dpp/cluster.h
- include/dpp/message.h
- include/dpp/queues.h
- src/dpp/cluster.cpp
- src/dpp/cluster/appcommand.cpp
- src/dpp/cluster/message.cpp
- src/dpp/message.cpp
- src/dpp/queues.cpp
> Revert "feat: add multiple attachments"

- .gitignore
- include/dpp/cluster.h
- include/dpp/message.h
- include/dpp/queues.h
- src/dpp/cluster.cpp
- src/dpp/cluster/appcommand.cpp
- src/dpp/cluster/message.cpp
- src/dpp/message.cpp
- src/dpp/queues.cpp
Think I fixed #231 
Added check for file name and contents to http_request constructor
> feat: add multiple attachments (take 2)

- include/dpp/cluster.h
- include/dpp/message.h
- src/dpp/cluster/role.cpp
- src/dpp/emoji.cpp
role position endpoint: https://discord.com/developers/docs/resources/guild#modify-guild-role-positions
> fix: role_edit_position and emoji::format didn't return animated emojis

- include/dpp/role.h
https://github.com/discord/discord-api-docs/commit/eca2d7fed256cbb997623012199b945bdf8cbb31
> docs: updated role_permissions

- docpages/04_advanced_reference.md
This pull request adds a "Unit Tests" page to the Advanced Reference section.
> add unit tests page

- docpages/02_building_a_bot.md
I've added a guide on how to use DPP using WSL 2 in case windows-people want an alternative to VS 2019/22
> added build-a-discord-bot-windows-wsl

- docpages/02_building_a_bot.md
deleted leftover html that didn't work and updated the link in the build-a-bot repl.it page
> delete leftover html and update link in the repl.it page

- docpages/03_example_programs.md
> Typos and stuff

- docpages/03_example_programs.md
Added blank I forgor in the webhook example
> Fixed the blank I forgor

- docpages/02_building_a_bot.md
updated the mentioned DPP version in the guides
> updated mentioned version

- include/dpp/role.h
- src/dpp/role.cpp
would be a breaking change ig
https://github.com/discord/discord-api-docs/commit/daa8fad16991f9071f48b2f1675e2f48f21cc1c3
> renamed start_embedded_activities

- include/dpp/message.h
- src/dpp/message.cpp
https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints
> added sticker::get_sticker_url getter

- docpages/02_build.md
Use a huge red warning box that will hopefully allow readers to know that they should read the stuff inside it, and use the template, instead of blindly following the instructions.
Looks like this now:
> use a red warning box

- src/dpp/message.cpp
Emoji button wasn't filled from json.
> Component button wouldn't get emoji info

- include/dpp/colors.h
as the title says I added color constants for quite some colors
> added color constants

- docpages/03_example_programs.md
just forgot to change that in the original PR
> made usage of color constant

- include/dpp/message.h
- src/dpp/message.cpp
on a select menu event, options were missing. This fixes that
> select_option fill from message's component was missing

- include/dpp/cluster.h
- src/dpp/cluster.cpp
> api: Ability to wait for cluster termination

- include/dpp/commandhandler.h
- include/dpp/dispatcher.h
The default callbacks were missing here.
> add missing default callbacks to some functions

- .clang-format
- .clang-tidy
These two files will let people know of their code format issues/warnings
Altho .clang-tidy won't run on code afaik so it's just for people who wanna code with improvements. It won't affect the current codebase
> Added .clang-tidy and .clang-format

- docpages/03_example_programs.md
It's not like i want some role or anything! Hmph
> Nullify undefined reference error :smiley:

- include/dpp/dispatcher.h
- src/dpp/dispatcher.cpp
> make return type of get_message and get_user const

- src/dpp/application.cpp
- src/dpp/auditlog.cpp
- src/dpp/ban.cpp
- src/dpp/channel.cpp
- src/dpp/discordevents.cpp
- src/dpp/emoji.cpp
- src/dpp/integration.cpp
- src/dpp/invite.cpp
- src/dpp/message.cpp
- src/dpp/presence.cpp
- src/dpp/prune.cpp
- src/dpp/role.cpp
- src/dpp/scheduled_event.cpp
- src/dpp/slashcommand.cpp
- src/dpp/webhook.cpp
Also uses the .contains function, instead of .find() and .end(), which is longer, and thus more prone to bugs
> fixes a bug with using .at

- src/dpp/discordvoiceclient.cpp
```txt
The break condition of the voice courier thread is incorrect. It is
checking the client user ID to parking lot map size, but it should
be checking whether there are any payloads to deliver.
```
> Fix discord_voice_client hanging in destructor, again.

- src/dpp/discordvoiceclient.cpp
Noticed that the energy consumption was high while using the voice client. Found that the condition isn't accurate since it always succeeds when at least one person has spoken.
```txt
The condition variable condition always succeeds, so it has no benefit
in improving energy consumption. Removing the condition because we
actually need to iterate over our containers (or introduce extra states,
which I am not a big fan of) to find out whether there are payloads to
deliver.
```
> Improve discord_voice_client energy.

- docpages/03_example_programs.md
- include/dpp/cluster.h
- include/dpp/permissions.h
- src/test.cpp
also added more unit testing for dpp::permission and some other doc updates
> added examples in the method docs of dpp::permission

- .gitignore
- Doxyfile
- include/dpp/message.h
- [misc] some common git ignores
- [fix] don't document deps
- [fix] docs typo
> Minor changes

- docpages/style.css
(preview of the changes using darkmode)
> make arrows in navigation always visible

- src/dpp/etf.cpp
> Updates - replacing a few push_backs with emplace_backs.

- include/dpp/appcommand.h
- src/dpp/slashcommand.cpp
> Add autocomplete support for subcommands arguments

- docpages/example_programs/interactions_and_components/subcommands.md
- Changed dpp::snowflake in subcommands docs to uint64_t
- Removed extra brackets in subcommands docs.
> Fixed subcommand docs

- include/dpp/cluster.h
- src/dpp/cluster.cpp
> Updates! Added a constructor argument for setting the gateway address. (Fixed a reference issue)

- include/dpp/channel.h
- include/dpp/cluster.h
- include/dpp/guild.h
- include/dpp/integration.h
- include/dpp/message.h
- include/dpp/role.h
- src/dpp/channel.cpp
https://github.com/discord/discord-api-docs/commit/7c5e883a61d8dbfab470731c4a70a73d9a5c1807
> breaking: rename "news" channel to announcement channel

- include/dpp/dispatcher.h
- src/dpp/events/guild_role_delete.cpp
> [fix] emit guild_role_delete_t when role isn't cached

- CODE_OF_CONDUCT.md
- README.md
more info: https://www.contributor-covenant.org/
> update code of conduct to v2.1

- src/dpp/discordvoiceclient.cpp
Updating to filter out the "silence frames" that muddy up the signal.
> Updating the DiscordVoiceClient.

- src/dpp/presence.cpp
This triggers my warning PTSD.
> Fix compiler warning

- src/dpp/discordvoiceclient.cpp
Prevent the sleep_increment from increasing over time
> Small fix in satype_overlap_audio

- include/dpp/voicestate.h
updated the docs to match the discord API:
https://discord.com/developers/docs/resources/voice#voice-state-object-voice-state-structure
> docs: updated the descriptions of dpp::voicestate_flags

- include/dpp/utility.h
- src/dpp/utility.cpp
same as rbg function gives abilities to use colors of such formats in embeds.
> added convertions from hex and cmyk colors to decimal value

- src/dpp/discordvoiceclient.cpp
> Implementing a "UDP-keepalive".

- include/dpp/cluster.h
- include/dpp/integration.h
- include/dpp/message.h
https://discord.com/developers/docs/resources/channel#message-object-message-types
updated some docs too
> feat: added new message type `mt_role_subscription_purchase`

- include/dpp/message.h
https://discord.com/developers/docs/resources/channel#message-object-message-types
> feature: Added Message types INTERACTION_PREMIUM_UPSELL & GUILD_APPLICATION_PREMIUM_SUBSCRIPTION

- docpages/example_programs/music_and_audio/oggopus.md
* Add liboggz as alternative to libogg
> doc: add liboggz

- include/dpp/appcommand.h
- include/dpp/dispatcher.h
- include/dpp/webhook.h
- src/dpp/dispatcher.cpp
- src/dpp/slashcommand.cpp
- src/dpp/webhook.cpp
> refactored webhook constructor & add_localization & get_parameter in context_menu_t and message_context_menu_t

- include/dpp/dispatcher.h
- include/dpp/message.h
- include/dpp/user.h
- src/dpp/dispatcher.cpp
this pr also updates some docs with embeds
> refactor: revert get_parameter to interaction_create_t from #641

- include/dpp/appcommand.h
- src/dpp/dispatcher.cpp
- src/dpp/slashcommand.cpp
reference: https://discord.com/developers/docs/change-log#april-6-2023
> feat: added channel object to interaction

- include/dpp/message.h
- include/dpp/permissions.h
- include/dpp/role.h
- src/dpp/message.cpp
- src/dpp/role.cpp
reference: https://github.com/discord/discord-api-docs/commit/70bc0f05a90b952f376ac2071dba52225dedf7c6
> feat: support for voice messages

- docpages/make_a_bot/windows_vs.md
- docpages/make_a_bot/windows_wsl.md
- include/dpp/sslclient.h
Removed opening vscode in separate window then navigating to WSL in favor of `code .` on the command line. Also, added a note on the Visual Studio 20xx page on the usefulness of WSL.
> Updated information regarding WSL

- include/dpp/automod.h
- include/dpp/guild.h
- src/dpp/automod.cpp
- src/dpp/guild.cpp
Reference: https://github.com/discord/discord-api-docs/commit/7467461237468e01f79ec2d88bcb8b77a024ea34
(i haven't tested the new features)
> feat: added join raid and mention raid protection feature

- include/dpp/integration.h
- src/dpp/integration.cpp
Integration object from discord's documentation: https://discord.com/developers/docs/resources/guild#integration-object-integration-structure
> feat: added i_guild_subscription integration type

- include/dpp/auditlog.h
https://github.com/discord/discord-api-docs/commit/dcabcef916eeaab84506c411bb10248873ea5931
> feat: add missing audit log events

- include/dpp/collector.h
- include/dpp/dispatcher.h
- src/dpp/events/message_reaction_add.cpp
https://github.com/discord/discord-api-docs/commit/095e858ee3838ebf343d408c8a6b31ed96e878e4
> feat: added message_author_id field to message_reaction_add_t event

- src/dpp/dispatcher.cpp
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105329
> fix: workaround gcc-12 bug #105329

- README.md
OpenSSF best practices badge - passing!
> OpenSSF best practices badge

- docpages/example_programs/interactions_and_components/context_menus.md
- docpages/example_programs/interactions_and_components/upload_parameter.md
- docpages/example_programs/music_and_audio/join_voice.md
Made a push for #771 to resolve reviews, but it didn't push in time and got missed. This fixes that issue and makes the docs actually in-line with the reviews.
> docs: Fix of #771 where final push was missed.

- src/dpp/discordevents.cpp
> fix: fix discordevents.cpp exports on windows

- docpages/example_programs/interactions_and_components/autocomplete.md
- docpages/example_programs/interactions_and_components/components.md
- docpages/example_programs/interactions_and_components/components2.md
- docpages/example_programs/interactions_and_components/components3.md
- docpages/example_programs/interactions_and_components/context_menus.md
- docpages/example_programs/misc/cache_messages.md
Some pages were missing "()". Tests were ran with "()" but it seems I forgot to simply add them when writing into these files.
Also added some spacing in places and removal of indentation in autocomplete.md where it wasn't needed.
I also restructured context_menus.md as it didn't follow the same structure as all other pages (which isn't too much of an issue but logically makes sense and it's good to keep a format established so people don't get confused).
On top of everything else, I removed the `using json` from components2.md and components3.md as it wasn't used.
> docs: Fixed some doc pages with errors.

- .clabot
- .github/pull_request_template.md
> ci: create .clabot for CLA agreements for new contribs

- .clabot
> ci: delete .clabot, not required for new cla/dco bot

- sign.sh
Improves code signing as some idiot at github decided to make artifacts not immutable.
https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/
> ci: force reupload with clobber, and sign a copy of the source archives

- docpages/example_programs/interactions_and_components/commandhandler.md
Just some simple edits to make it more applicable
> Docs: Modernize command handle page

- include/dpp/application.h
- src/dpp/application.cpp
Implements [application team member roles](https://discord.com/developers/docs/topics/teams#team-member-roles)
Implements https://github.com/discord/discord-api-docs/pull/6372
> feat: application team member roles feature

- README.md
> docs: add emojis to titles in readme

- README.md
This PR adds a section about Nightly Builds to the README.md as previously discussed in the discord.
I'm not entirely sure on the wording with this so please feel free to discuss the wording of this if you feel this could be worded in a better way.
> docs: changed README.md to include nightly builds.

- docpages/01_frequently_asked_questions.md
- docpages/example_programs/using_coroutines.md
- docpages/example_programs/using_coroutines/awaiting_events.md
- docpages/example_programs/using_coroutines/coro_introduction.md
- docpages/example_programs/using_coroutines/coro_simple_commands.md
- docpages/example_programs/using_coroutines/expiring_buttons.md
> docs(coro): small touches

- .gitignore
This PR cleans up .gitignore, creating sections for different types of ignored files/folders. This also adds .idea to the ignore file as we don't currently ignore that.
> refactor: organised .gitignore, added .idea to ignore

- docpages/example_programs/the_basics/embeds.md
This PR fixes a typo in embeds.md
Thanks to @Jaskowicz1
> docs: fixed an issue in embeds.md

- src/dpp/discordvoiceclient.cpp
> fix: wrong size assignment

- include/dpp/isa_detection.h
Realized that I had done this wrong in the previous implementation. Also edited the name of a variable.
> fix/voice: Updating to fix the clamping behavior of the AVX-512 implementation.

- README.md
added minimum required clang version to README
> docs: added minimum required clang version

- src/dpp/wsclient.cpp
> fix: base64 sslclient key

- .github/workflows/test-docs-examples.yml
> ci: cancel concurrent test docs examples

- src/dpp/dtemplate.cpp
This PR just removes some blank lines in dtemplate.cpp. It also serves as a quick check to see if labeler is working as intended.
> style: removed blank lines in dtemplate

- include/dpp/discordevents.h
- src/dpp/discordevents.cpp
> build: fix #926, speedrun to #1000

- docpages/example_code/resolved_objects.cpp
- docpages/example_programs/interactions_and_components.md
- docpages/example_programs/interactions_and_components/resolved_objects.md
> DOCS: added resolved object example

- include/dpp/managed.h
- include/dpp/snowflake.h
++gcc_is_not_a_valid_cpp_compiler;
> fix: fix clang c++17 build

- .github/workflows/ci.yml
updates ci action dependency to latest master
> ci: bump gha-setup-ninja

- include/dpp/appcommand.h
> fix: fix interaction_modal_response's ambiguous to_json

- library-vcpkg/CMakeLists.txt
> ci: fix vcpkg surely

- include/dpp/nlohmann/json.hpp
- include/dpp/nlohmann/json_fwd.hpp
This PR updates nlohmann json to 3.11.2.
This was originally done in #982, but we've heard nothing back and we aren't 100% sure this works (our CIs do say this works, but a real test case is required for this as it's a huge change).
> build: updated nlohmann to 3.11.2

- buildtools/emojis.php
- include/dpp/message.h
- include/dpp/misc-enum.h
- include/dpp/role.h
- include/dpp/scheduled_event.h
- include/dpp/sku.h
- include/dpp/stage_instance.h
- include/dpp/timed_listener.h
- include/dpp/timer.h
- include/dpp/unicode_emoji.h
- include/dpp/user.h
- include/dpp/utility.h
- include/dpp/voiceregion.h
- include/dpp/voicestate.h
- include/dpp/webhook.h
- include/dpp/wsclient.h
This PR is the final refactor to comments (continuation from #979, part 4)! Now we can relax knowing our comments follow the coding style guide.
> style: the final comments refactor.

- docpages/building/linux.md
- docpages/example_programs/the_basics/firstbot.md
- docpages/install/install-arch-aur.md
Reverts brainboxdotcc/DPP#1013
> Revert "docs: changes to buildlinux, firstbot, and install-arch-aur."

- include/dpp/message.h
- src/dpp/message.cpp
> fix: send stickers in message if present

- src/dpp/cluster/confirmation.cpp
The error parser would stop at the first field (here "thumbnail") on something like this, and show "Invalid Form Body":
```json
{
"message": "Invalid Form Body",
"code": 50035,
"errors": {
"embeds": {
"0": {
"thumbnail": {
"url": {
"_errors": [
{"code": "URL_TYPE_INVALID_URL", "message": "Not a well formed URL."}
]
}
}
}
}
}
}
```
> fix: fix bug in human readable errors

- .vscode/settings.json
- src/dpp/cluster/timer.cpp
> FIX: dont attempt to reschedule timers that are deleted (FIXES: #1048)

- include/dpp/queues.h
- src/dpp/cluster.cpp
- src/dpp/queues.cpp
fixes https://github.com/brainboxdotcc/DPP/issues/1091
truly a GNU moment
> fix memory leak on libstdc++

- src/dpp/discordevents.cpp
> FIX: Silence GUILD_SOUNDBOARD_* websocket events, currently undocumented

- include/dpp/queues.h
- src/dpp/queues.cpp
> fix: fix leak of in_thread, fix read-after-free, fix race condition UB after cluster shutdown

- cmake/CPackSetup.cmake
> Updated libsodium version for rpm packages to latest

- include/dpp/coro/awaitable.h
> fix(coro): fix an oopsie

- include/dpp/isa/neon.h
Adds a fix to the bug in the code that Brain found.
> Adding fix to arm-neon bug.

- src/dpp/guild.cpp
> fix: fix guild_member::get_avatar_url() (#1230)

- .github/workflows/ci.yml
> ci: fix mac xcode version

- .github/workflows/ci.yml
> ci: add clang-19-libc++ as manual install

- .github/workflows/ci.yml
> ci: more secure llvm19 install process

- include/dpp/message.h
- src/dpp/message.cpp
Adds support for message forwarding, message_reference type 1, plus message_snapshots structure in message (an array of messages)
> Message forwarding

- src/dpp/voice/enabled/opus.cpp
removes an unused variable that was left in from removing sodium
> refactor: remove unused debug variable

- README.md
> docs: prevent "The Windows 7 Incident"

- docpages/advanced_reference/roadmap.md
We hadn't updated this and coro is essentially stable now.
Added new roadmap features.
For discussion: is this page best place to store a roadmap, it isn't very community driven.
> docs: update roadmap

- CMakeLists.txt
Added definition of NOMINMAX to cmake. This will avoid conflicts with windows macros when compiling for windows.
* [Code Changes](?expand=1&template=code_change_template.md)
* [Documentation Changes](?expand=1&template=docs_change_template.md)
> Added NOMINMAX to CMakeLists.txt

- README.md
adds Conan shields.io badge to readme
- x ] I tested that my change works before raising the PR (via running `doxygen`, and testing examples).
> docs: conan badge

- README.md
> docs: fix codacy badge

- src/dpp/socketengines/poll.cpp
> fix: we never remove fds that want deletion

- src/dpp/cluster.cpp
> misc: execute on_stop callback of all timers on bot shutdown

- src/unittest/test.cpp
- src/unittest/test.h
This PR adds channel_invites_get to the unit test.
> feat: added channel_invites_get to unit tests
