- include/dpp/cluster.h
- src/dpp/cluster.cpp
- src/test.cpp
added pins_get to get channel pins
example test code:
```c++
bot.pins_get(event.msg->channel_id, [log, &bot](const dpp::confirmation_callback_t& completion) {
dpp::message_map pins = std::get<dpp::message_map>(completion.value);
log->debug("Pins got! number of pins={} http status={}", std::distance(std::begin(pins), std::end(pins)), completion.http_info.status);
});
```
this PR also includes fixes to `channel_edit_permissions` and `channel_invites_get`, as they were using the `/api/channel` endpoint instead of `/api/channels`
pins_get has been tested, the fixes to `channel_edit_permissions` and `channel_invites_get` have **not** been tested.
> added pins_get to get channel pins

- include/dpp/cluster.h
- src/dpp/cluster.cpp
added these two functions:
```cpp
/** Adds a recipient to a Group DM using their access token */
void gdm_add(snowflake channel_id, snowflake user_id, const std::string &access_token, const std::string &nick, command_completion_event_t callback);
/** Removes a recipient from a Group DM */
void gdm_remove(snowflake channel_id, snowflake user_id, command_completion_event_t callback);
```
> add gdm_add and gdm_remove

- include/dpp/cluster.h
- include/dpp/discord.h
- include/dpp/dtemplate.h
- include/dpp/invite.h
- src/dpp/cluster.cpp
- src/dpp/dtemplate.cpp
introduces a dtemplate and dtemplate_map class and the following functions
```cpp
/** Get a template */
void template_get(std::string code, command_completion_event_t callback);
/** Create a new guild based on a template. */
void guild_create_from_template(std::string code, std::string name, command_completion_event_t callback);
/** Get guild templates */
void guild_templates_get(snowflake guild_id, command_completion_event_t callback);
/** Creates a template for the guild */
void guild_template_create(snowflake guild_id, std::string name, std::string description, command_completion_event_t callback);
/** Syncs the template to the guild's current state. */
void guild_template_sync(snowflake guild_id, std::string code, command_completion_event_t callback);
/** Modifies the template's …
```
> guild templates

- include/dpp/message.h
- src/dpp/message.cpp
I couldn't link to the library on Mac when building the master branch, as clang complained about the `component` constructor. This PR just sets the constructor to `default`, which fixes the issue.
This is just a preface to another PR I'm gonna make, to load the attachments in the message_create event. :D
> Make component destructor the default constructor

- include/dpp/message.h
- src/dpp/message.cpp
Discord sends a list of all attachments in the JSON when transmitting a message object. Similarly, under certain circumstances a list of all reactions is transmitted. This PR adds both infos to the `dpp::message` object.
Firstly, there's a new attachment struct. It closely follows the [official docs](https://discord.com/developers/docs/resources/channel#attachment-object) on what's present and what not.
Secondly, I've added one field to dpp::reaction, the emoji name. Discord sends it, and for non-custom reactions, this is often the only way to figure out which emoji was used to react.
Both are populated accordingly.
> Handle attachments and reactions for messages

- include/dpp/slashcommand.h
- src/dpp/slashcommand.cpp
As discussed on #18 , there is an issue with the json serialization when we have sub-commands with options
Based on https://github.com/nlohmann/json#arbitrary-types-conversions I created three `to_json` functions, one to serialize slashcommand, one to command_option and one to command_option_choice, the main function `build_json` is now much simpler and just creates the json object and adds the id field if necessary, the conversion is done automatically via each function.
> Change slashcommand json serialization

- include/dpp/discordevents.h
- include/dpp/guild.h
- include/dpp/slashcommand.h
- include/dpp/user.h
- src/dpp/discordevents.cpp
- src/dpp/guild.cpp
- src/dpp/slashcommand.cpp
- src/dpp/user.cpp
This fixes a similar issue to #18 #19 but the other way around, received interaction events had their sub-options ignored and not parsed, this used the json's library built-in `from_json` to make this deserialization easier.
The original `::fill_from_json` methods are still there and just call the automatic conversion from the library, for compatibility, also, I onlyu implemented this for the structs involved in the interatcion_create event, the others are still parsed as they used to be.
> Implement json deserializers for interaction events

- include/dpp/slashcommand.h
- src/dpp/slashcommand.cpp
Command interaction options with integer type (`dpp::co_integer`) can have signed values, this is taken directly form the discord json:
This PR changes unsigned to signed
> Change command_value to accept signed integers

- include/dpp/httplib.h
- include/dpp/sslclient.h
This commit fixes errors about random missing symbols (or redefined) on OpenSSL headers. This has been tested and works on my machine.
> Fix OpenSSL for Windows

- src/dpp/message.cpp
Library was not adding the timestamp field to the json object
> Fix: timestamp not part of build_json output

- src/dpp/dispatcher.cpp
While working with long (>16 chars) slash command parameters, I ran into some issues with parts of the data getting corrupted, and after some examination the problem seems to be the following:
`std::get` in `command_interaction ci = std::get(...` returns a `const command_interaction&`, but the assignment to a non-reference type creates a local copy on the stack. The `const command_value&` returned by the function is therefore a reference to a local object. Changing the type of `ci` from `command_interaction` to `const command_interaction&` seems and ought to have fixed the problem, as it preserves the reference returned by `std::get` instead of creating a local copy.
> interaction_create_t::get_parameter returns reference to value on the stack

- docpages/02_build.md
Block code have some rendering issue in the documentation (file: `docpages/02_build.md`):
> fix block code in documentation

- include/dpp/cluster.h
- include/dpp/dispatcher.h
- src/dpp/cluster.cpp
- src/dpp/dispatcher.cpp
This updates `cluster::interaction_response_edit` to use the proper api endpoint (`/api/v8/webhooks`) and format in accordance with https://discord.com/developers/docs/interactions/slash-commands#edit-original-interaction-response. Some unnecessary parameters were removed. Also added `interaction_create_t::edit_response`.
> Finished implementing editing of slash command interaction responses

- src/dpp/cluster.cpp
- src/dpp/slashcommand.cpp
Currently, the `permissions` vector is not being included in the json from what I can tell. This updates the appropriate `to_json` function to now also include the permissions, basically using the same code that is used to convert the other vectors to json. The `cluster::guild_command_edit_permissions` function also needs that vector, so I added the same code there as well. I tested it and for me, it's working now.
It might also be worth considering refactoring this into a template of some sort, since there are multiple instances throughout the code where that logic is used in exactly the same way.
> Fixed slash command permissions not being included in json

- include/dpp/guild.h
- src/dpp/guild.cpp
The other ones are defined, but not is_pending(). That's it.
> Added missing is_pending() like the other ones to guild_member

- include/dpp/slashcommand.h
Values 6 and 7 were missing.
Based on https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type
> Add new interaction_response_type types

- include/dpp/message.h
- src/dpp/message.cpp
Interaction is a good way to get who triggered the bot's message if that was from a slash command.
Sources:
- Message Interaction structure: https://discord.com/developers/docs/interactions/receiving-and-responding#message-interaction-object-message-interaction-structure
- Message object: https://discord.com/developers/docs/resources/channel#message-object
> Add interaction feature to dpp::message

- src/dpp/cluster.cpp
Maybe create a custom exception class in the `dpp` namespace so exceptions from DPP can be filtered?
Ex:
```cpp
#include <utility> // std::in_place_t
#include <exception> // std::exception
namespace dpp {
class exception : public std::exception
{
std::string msg;
public:
using std::exception::exception;
exception() = default;
explicit exception(const char* what) : msg(what) { }
exception(const char* what, size_t len) : msg(what, len) { }
explicit exception(const std::string& what) : msg(what) { }
explicit exception(std::string&& what) : msg(std::move(what)) { }
template < class... Args > explicit exception(std::in_place_t, Args&&... args)
: msg(fmt::format(std::forward< Args >(args)...)) { }
exception(const exception&) = default;
exception(exception&&) = default;
~exception() override = …
```
> std::exception does not have a constructor that takes in a string.

- src/dpp/discordevents.cpp
Mainly gets rid of the compiler ISO warning. The issue still remains but the intention is now obvious.
> Explicitly remove the const qualifier from string literal.

- src/dpp/cluster.cpp
- src/dpp/message.cpp
I was having a hard time using a webhook to both post messages and use a user provided username.  These changes worked for me.
* Use the webhook token, if provided otherwise fall back to previous behavior (bot token).  According to the API documentation this should be a webhook token, not the bot token
* Add "username" to messages if there is an author, currently only used for execute_webhook
> Webhook Adjustments

- include/dpp/message.h
- src/dpp/message.cpp
As added to the discord api docs, the attachment now has a ephemeral boolean. Added the json support for this new boolean.
docs commit:
https://github.com/discord/discord-api-docs/commit/670f33f6b3c5dff2993c497be9e5a8ea35e2cb57#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95
> Add ephemeral boolean to attachment.

- src/dpp/cluster.cpp
Endpoint expects 'nick', not 'nickname'.
> Fix guild_set_nickname bug

- CMakeLists.txt
- dpp.pc.in
Makes it easier to integrate DPP into builds using systems other than CMake. Not entirely sure if anything else needs to be added to the `Libs:` line, but it has been working for me as-is.
> Generate pkg-config file

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
- Add send_audio_opus method overload that calculates duration of packet internally
> feat: calculate opus packet duration internally

- include/dpp/guild.h
- include/dpp/user.h
- src/dpp/guild.cpp
- src/dpp/user.cpp
- updated docs of avatar size: https://discord.com/developers/docs/reference#image-formatting-image-base-url
- so `uint16_t` should be enough ig
> updated docs of avatar size

- src/dpp/slashcommand.cpp
fix #209 
The slash command permissions works now. I changed it so that the `autocomplete` field only get send, when its true.
I've also tested slash command autocompletion with these changes and they still works
(tested with the example https://dpp.dev/application-command-autocomplete.html).
> fixed slash command permissions not working

- include/dpp/cluster.h
- src/dpp/cluster/appcommand.cpp
seems like these lines were there before https://github.com/brainboxdotcc/DPP/blob/f8e48910d0586b028a9495bd28078b1fa911c577/src/dpp/cluster.cpp#L385-L387
The parameter `s` will change to a non-const parameter this could be a breaking change?!
Shouldn't we change that also in `global_command_create` and other methods @braindigitalis ?
#212
> add fix to guild_command_create to solve the permissions edit issue

- src/dpp/cluster/appcommand.cpp
fixes slash command permissions not being applied on creation of guild command
> 212 fix slashcommand permissions

- src/dpp/cluster/thread.cpp
when calling those, they breaks the execution of the programm
```json
terminate called after throwing an instance of 'nlohmann::detail::type_error'
what():  [json.exception.type_error.305] cannot use operator[] with a string argument with boolean
```
- fixed and tested `threads_get_active`
- fixed and tested `threads_get_public_archived`
- fixed `threads_get_private_archived`
- fixed `threads_get_joined_private_archived`
> fix: several thread-getters were broken and breaks the program

- .gitignore
- include/dpp/cluster.h
- include/dpp/message.h
- include/dpp/queues.h
- src/dpp/cluster.cpp
- src/dpp/cluster/appcommand.cpp
- src/dpp/cluster/message.cpp
- src/dpp/message.cpp
- src/dpp/queues.cpp
- Add the ability to add multiple attachment to messages as suggested in issue #181 
- Add .idea to gitignore for CLion
This does not break any of the existing methods (`set_filename`, `set_file_content`) but instead adds another method called `add_file` to the message class
> feat: add multiple attachments

- CMakeLists.txt
This PR exports the `include/` directory to any other CMake project who may want to include `dpp` as a source-dependency instead of building it system-wide. This makes the project more compatible with modern CMake practices and also makes it possible to install out-of-the-box using package managers like [CPM](https://github.com/cpm-cmake/CPM.cmake).
> Export include directory to external CMake targets

- src/dpp/guild.cpp
This is not a bulletproof fix (just a workaround i think) because when you edit a guild_member who has administrator permissions or is admin, it will fail.
See documentation here https://discord.com/developers/docs/resources/guild#modify-guild-member.
#251
> quickfix guild_edit_member

- docpages/02_build.md
(previous PR was to the wrong branch)
This replaces using:
```
mkdir build
cd build
cmake ..
make -j8
```
with just:
```
cmake -B ./build
cmake --build ./build -j8
```
It does the same thing, but uses `cmake` instead, has less steps, and shows color.
It also specifies that Visual Studio 2022 is allowed, not just Visual Studio 2019.
> update build docs

- docpages/02_build.md
right now, the docs show that you should run `make install` from the root dir, while you should do so from the `./build` dir. This PR fixes it.
> fix wrong make install dir

- CMakeLists.txt
- cmake/libdpp-config.cmake
On Apple Silicon macbooks, brew's root directory is `/opt/homebrew/` instead of `/usr/local/`, so the the code needs to be updated to fix that.
> fix for apple silicon

- src/dpp/cluster/message.cpp
commit 5a83595da5ac753127b25917469f72cef46db071 broke this.
Only this one http method was broken. All the others should be correct. I manually looked through all of them.
> fix wrong http method

- src/dpp/message.cpp
fill_from_json on dpp::message didn't load components of message.
> Components were not considered on fill_from_json

- include/dpp/message.h
- src/dpp/message.cpp
component didn't have a set_required like other properties do.
> set_required was not available on component like the other properties

- include/dpp/channel.h
- src/dpp/channel.cpp
You can't set the guild_id using functions, so this PR adds it.
> add set_guild_id to channel

- include/dpp/cluster.h
- include/dpp/timer.h
- src/dpp/cluster/timer.cpp
- src/test.cpp
For when you don't want to manage a lifetime of object which holds `dpp::timer` handle such as `dpp::oneshot_timer` and still be able to stop the timer without convoluted pointers to it's ID.
> break: Add parameter dpp::timer to timer_callback_t

- cmake/ARM64ToolChain.cmake
This should fix arm64 toolchain not compiling because of a missing libc6 package.
> Add dependency libc6-dev-arm64-cross for arm64 toolchain

- include/dpp/sync.h
relying on timer doesn't look right.
> faster and more reliable thread blocking in dpp::sync

- include/dpp/message.h
Adds the missing virtual destructor for `select_option` that was causing a lot of warnings.
> add destructor for select option

- include/dpp/dispatcher.h
- src/dpp/dispatcher.cpp
Adds `get_original_response`, `edit_original_response`, and `delete_original_response`. These functions are documented [here](https://discord.com/developers/docs/interactions/receiving-and-responding#get-original-interaction-response).
> Add get, edit, and delete original response functions

- include/dpp/message.h
- src/dpp/message.cpp
`set_channel_id` and `set_guild_id` were missing in `dpp::message`
> add set_channel_id and set_guild_id to message

- src/dpp/dispatcher.cpp
Copying the value of creator (the `dpp::cluster*`) makes the value valid. "this" as "interaction_create_t" is not (after some time). That can (and probably will) segfault.
> Fixed "this" could be invalid when callback was called on post_rest because interaction_create_t is not valid after an interaction event returns

- src/dpp/cluster/appcommand.cpp
This endpoint can be used to delete all global/guild commands by passing an empty array.
> Allow an empty vector of commands for bulk command create

- include/dpp/cluster.h
remove unused `using namespace std::placeholders;`
> remove unused line

- src/dpp/guild.cpp
Before, it wouldn't get unset bc it wouldn’t be put into the JSON. This PR fixes it.
> Properly set deaf and mute properties on member

- src/dpp/discordclient.cpp
I created a slash command that lets the user tell the bot to join a specified voice channel. As shown in [this example](https://dpp.dev/joinvc.html), the bot needs to disconnect from its current voice channel before joining another voice channel in the same guild. The app always crashes on my M1 Mac (though in theory it should not be limited to Macs) at disconnection time, using `dpp::discord_client::disconnect_voice` from within the `on_interaction_create` handler.
With the help of ASAN I was able to identify the crash as a double-free.
```txt
At connection time, voiceconn creates a voice client, which handles
the closing of its underlying SSL client in the destructor. However,
at disconnection time, dpp::voiceconn also attempts to close the voice
client before deleting it. This …
```
> Fix double-free of SSL client through dpp::voiceconn when disconnecting from a voice channel.

- src/dpp/cluster/guild_member.cpp
Was using this API to fetch the guild nickname of the speaking users in a voice channel. Found that this API always returns an empty map. Removing them solved my issue.
```txt
The quotes in the query becomes literal, which causes Discord to
look for quotes in the username and nickname. Without this change,
the resultant member map is empty unless the nickname really
contains quotes.
```
> Remove extraneous quotes around guild member search query.

- include/dpp/appcommand.h
- include/dpp/channel.h
- include/dpp/dtemplate.h
- include/dpp/emoji.h
- include/dpp/guild.h
- include/dpp/integration.h
- include/dpp/invite.h
- include/dpp/json_interface.h
- include/dpp/message.h
- include/dpp/presence.h
- include/dpp/prune.h
- include/dpp/role.h
- include/dpp/scheduled_event.h
- include/dpp/stage_instance.h
- include/dpp/sync.h
- include/dpp/user.h
- include/dpp/voicestate.h
- include/dpp/webhook.h
The synced functions sometimes indefinitely block. All other threads are waiting for work to do, so it appears the condition variable is waited after the rest request is completed. The lambda probably needed to lock the mutex before signaling to ensure the calling thread started the wait.
Anyway, thought that promises and futures are cleaner so switched to using those. Calling thread is no longer indefinitely blocked.
Also refactored `json_interface` since I encountered some warnings and thought those are valid things to fix.
```txt
Switch synchronized calls from a condition variable to a promise.
Occasionally the synchronized call blocks indefinitely: the request
has been fulfilled before the calling thread starts waiting. This
can in theory happen in certain thread scheduling order. …
```
> Switch synchronized calls from a condition variable to a promise.

- docpages/03_example_programs.md
- include/dpp/appcommand.h
- src/dpp/slashcommand.cpp
- `set_name` sets the command name to lowercase only when the type is ctxm_chat_input
fix #373
> improved context menu example & updated set_name

- include/dpp/discordvoiceclient.h
- include/dpp/dispatcher.h
- src/dpp/discordvoiceclient.cpp
When there are multiple speakers, the voice data received from `on_voice_receive` callback was wrong. After lots of trial and error, it turns out Opus decoders are stateful, so using the same decoder to decode for all speakers jams the audio data together in a weird way. The main fix is to use a unique decoder for each speaker, but this change also contains a number of refactors and fixes as a result of the trial and error.
```txt
1. Allocate an Opus decoder for each speaker. Opus decoders are stateful,
so when there are multiple speakers, using one decoder will mess up the
voice data of every speaker.
2. Add handling for out-of-order UDP packets. UDP packets can arrive
out-of-order so it is up to the application to handle such cases. We
now does reordering for packets and flush them to …
```
> Improve voice receive handling.

- src/dpp/discordvoiceclient.cpp
Fixed `voice_client` but didn't fix `user_id`. Sigh.
> Fix missing user_id field in voice_receive_t in case of lost packet.

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
The voice I receive has rather low amplitude. Didn't want to do audio processing myself. Found that Opus decoder supports native gain control, so made this change to allow clients to set the gain, just like how the Discord client allows setting individual volumes for each speaker. This also affects the combined audio, which means clients can use this API to mute a certain user in the combined audio as well.
```txt
Similar to the User Volume slider in the Discord client, the bot
can choose the volume that it wants to hear a specific user at.
Uses native Opus decode gain control.
```
> Support gain control per user.

- src/dpp/discordvoiceclient.cpp
Sorry for not noticing until after the release 👀.
```txt
If the voice courier thread waits because of no voice data, it can
hang forever in the destructor because the thread is never signaled
to unblock (unless woken up by a spurious wake). This change adds
the signaling in the destructor to unblock a waiting courier thread.
```
> Fix potential hang in discord_voice_client destructor.

- src/dpp/discordvoiceclient.cpp
```txt
Previously, the condition depended also on the sequence number.
This was supposed to handle the wrap around case. In reality,
it depends on what LHS and RHS are, and flipping the LHS and RHS
breaks the ordering.
Recall that LHS has lower priority, i.e. should appear behind, RHS if
LHS.seq > RHS.seq || LHS.timestamp > RHS.timestamp
The timestamp is only taken into account if LHS.seq <= RHS.seq.
For example, in case of LHS.seq = 1 < 65530 = RHS.seq, the
timestamp will be taken into account, which could place
LHS (1) after RHS (65530). However, if we flip the sides, so that
LHS.seq = 65530 and RHS.seq = 1, then LHS (65530) is immediately
placed after RHS (1), without considering the timestamp, which is
incorrect behavior.
The consequence is that the ordering in the payload queue is …
```
> Depend `discord_voice_client::voice_payload` priority only on timestamps.

- src/dpp/guild.cpp
> \* User mentions with an exclamation mark are deprecated and should be handled like any other user mention.
https://discord.com/developers/docs/reference#message-formatting-formats
> removed deprecated exclamation mark from guild_member::get_mention

- include/dpp/appcommand.h
- src/dpp/channel.cpp
- src/dpp/slashcommand.cpp
> You can set it to 0 to disable the command for everyone except admins by default
source https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure
<hr>
* implemented channel::get_icon_url although the endpoint is not documented in the docs. but i found the url with the browser debugger :D
> implemented channel::get_icon_url & small doc improvements of slashcommand.h and some intent fixes

- include/dpp/appcommand.h
- include/dpp/application.h
- include/dpp/channel.h
- include/dpp/cluster.h
- include/dpp/cluster_sync_calls.h
- include/dpp/dpp.h
- include/dpp/guild.h
- include/dpp/permissions.h
- include/dpp/role.h
- include/dpp/utility.h
- src/dpp/channel.cpp
- src/dpp/cluster/channel.cpp
- src/dpp/guild.cpp
- src/dpp/permissions.cpp
- src/dpp/role.cpp
- src/test.cpp
- src/unittest.cpp
- **renamed `dpp::role_permissions` to `dpp::permissions`**, but added `using role_permissions = permissions;` so it shouldn't be too much breaking. I also moved it to a new file `permissions.cpp`.
- **Added constructor for `dpp::permission_overwrite`**
- **The has_-getters in `dpp::role` are now using the utility methods of `dpp::permission`**
The class holds an `uint64_t` and has some utility methods to check, remove and add flags.
This new class is now used for permission bitmasks and i replaced the old uint64_t with it on various places.
> permissions rework

- include/dpp/appcommand.h
- include/dpp/cluster.h
- include/dpp/cluster_sync_calls.h
- src/dpp/cluster/guild_member.cpp
- src/dpp/cluster_sync_calls.cpp
- src/test.cpp
the name guild_member_delete_role is just confusing because it doesnt delete anything, its just removing the role...
> added dpp::cluster::guild_member_remove_role and deprecated dpp::cluster::guild_member_delete_role

- include/dpp/permissions.h
makes it actually be a compiler error when you input something invalid
> add template to only enable for int convertible types

- src/dpp/discordvoiceclient.cpp
Using a web client to provide voice, found that the voice courier thread can easily run into the same symptoms as that prior to #391.
Turns out there can be multiple payloads with the same timestamp, so the approach of depending only on timestamps breaks the payload ordering and doesn't work. Have to bring back sequence number comparison.
Also hopefully now it should be properly handling the wrap around case for sequence number.
```txt
Seems to be prevalent in payloads from web clients; two payloads
with different sequence numebrs can have the same timestamp. We can't
be lazy and not look at the sequence number to order the payloads.
```
> Fix `discord_voice_client` `voice_payload` priority when two payloads have the same timestamp.

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
Was trying to send live audio data to a voice channel. Observed that the audio data has occasional silence and speed
changes. Determined that the sleep in `discord_voice_client::write_ready` contributed to the issue. However, it seems
that the sleep is useful for recorded data to simulate VoIP, so adding an option to effectively turn it on/off and enables
both use cases.
```txt
So far, the primary use case for sending audio data has been sending
recorded audio, which usually has large chunks of data available
instantly. Built-in throttling simulates the VoIP behavior where data
becomes available over time.
For live audio, however, built-in throttling isn't necessary because
the throttling is already inherent in capturing live audio. Extra
throttling can cause delays in delivering the …
```
> Added a voice client option to skip throttling for live audio data.

- include/dpp/guild.h
- src/dpp/guild.cpp
set_deaf and set_mute now set a bitflag, guild_member_update only sets deaf and mute parameters if the flag is on.
Provides a fix for the bug i found and that is described in #417
> Added voice action bitflag for guild_member fixed #417

- .cspell.json
- include/dpp/automod.h
- include/dpp/cluster.h
- include/dpp/cluster_sync_calls.h
- include/dpp/dispatcher.h
- include/dpp/event.h
- include/dpp/intents.h
- src/dpp/automod.cpp
- src/dpp/cluster/automod.cpp
- src/dpp/cluster/webhook.cpp
- src/dpp/cluster_sync_calls.cpp
- src/dpp/discordevents.cpp
- src/dpp/dispatcher.cpp
- src/dpp/events/automod_rule_create.cpp
- src/dpp/events/automod_rule_delete.cpp
- src/dpp/events/automod_rule_execute.cpp
- src/dpp/events/automod_rule_update.cpp
- src/dpp/webhook.cpp
closes #420 
implements:
https://discord.com/developers/docs/change-log#auto-moderation
https://github.com/discord/discord-api-docs/pull/4860 
https://github.com/discord/discord-api-docs/pull/5063
https://github.com/discord/discord-api-docs/pull/5083
* implements: automod REST endpoints: `cluster::automod_rules_get()`, `cluster::automod_rule_get()`, `cluster::automod_rule_create()`, `cluster::automod_rule_edit()`, `cluster::automod_rule_delete()`, `cluster::automod_rules_get_sync()`, `cluster::automod_rule_get_sync()`, `cluster::automod_rule_create_sync()`, `cluster::automod_rule_edit_sync()`, cluster::automod_rule_delete_sync()
* auto moderation websocket events: `on_automod_rule_execute`, `on_automod_rule_create`, `on_automod_rule_update`, `on_automod_rule_delete`
* serialisation …
> Automod REST endpoints, websocket events, JSON structures

- include/dpp/channel.h
- include/dpp/cluster.h
- include/dpp/guild.h
- src/dpp/channel.cpp
- src/dpp/guild.cpp
The following permissions getters calculated the permissions wrong. Discord probably changed the permission hierarchy. However the methods didn't follow the correct permission hierarchy.
- `channel::get_user_permissions()`
- `guild::base_permissions()`
- `guild::permission_overwrites()`
btw some of them didn't checked for null pointer.
I also added the same getters with `guild_member` param and references instead of pointers, because the don't require the user cache then.
Im wondering why the old ones got the `user` param, as they're immediately searching for the guild member in cache and doesn't really need the user.
They all still requires the role cache as they go through the roles etc.
I also updated some comments in this pr :)
The whole thing is tested of course.
**Additional …
> fixed permissions getter like channel::get_user_permissions

- src/dpp/cluster/webhook.cpp
1. It wasn't possible to edit webhook to change avatar, so edited it to use `wh.avatar`
2. This will override message.author.username if `wh.name` present
> fix: make execute_webhook supports avatar

- src/dpp/dns.cpp
* The new DNS feature uses unique_lock with shared_mutex
* This requires mutex include in gcc 11+, clang 12.0.1+
Fixes #434
> 🐛 Fix DNS mutex include

- .cspell.json
- include/dpp/automod.h
- include/dpp/message.h
- include/dpp/utility.h
- src/dpp/message.cpp
added [discord's keyword matching strategies](https://discord.com/developers/docs/resources/auto-moderation#auto-moderation-rule-object-keyword-matching-strategies) to `dpp::automod_metadata::keywords`
maked the second param of utility::timestamp optional!
> some docs updated

- src/dpp/etf.cpp
This change seems to increase the rate at which Dpp parses a data structure that comes in as a string that is 450k characters in length, by roughly 67%.
> Changes to increase parsing rate.

- src/dpp/queues.cpp
Replaces a `std::map` runtime construction/lookup with a constant runtime index into a constexpr array. This removes heap allocations that would otherwise be made for every http request made by the library/client.
Downsides: Potential for unseen errors if values outside of the typical range for `http_method` are passed (not worth considering). Potential for error if more `http_method` options are added in the future and the map is not updated (maybe worth considering).
Alternatives - make the map static, use a static `unordered_map` instead (no clue if it's more performant in this specific instance, but it should be generally), make a `to_string` function for `http_method` to increase coupling/decrease risk of not updating the mapping.
> Suggestion: Replace map with array.

- src/dpp/guild.cpp
json field `afk_timeout` addition was depending on another field's validity.
> Fix small issue in guild::build_json()

- library/CMakeLists.txt
CMAKE_APPLE_SILICON_PROCESSOR can be set to either x86_64 or arm64. This line of code must check for arm64 to set the correct path.
> Fixed AppleSilicon check

- include/dpp/cluster.h
- src/dpp/cluster/guild.cpp
https://github.com/discord/discord-api-docs/commit/7e3e3a3de46a909c9a5bc04404f0df9a806e7271
> breaking: delete message count on `cluster::guild_ban_add` is now scaled in seconds instead of days

- include/dpp/intents.h
Same as `i_default_intents` but also has `i_message_content` intent.
> Added unverified bots default intent.

- src/dpp/message.cpp
- src/dpp/slashcommand.cpp
- Issue: The permissions of the invoking member of an interaction was missing. [Because they're send within the member field](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure) and wasn't parsed. They're now parsed into the resolved set of the interaction object.
- The ctor of dpp::component are now using the proper enum value instead of the cast
> fix: permissions for the invoking member in an interaction_create_t event wasn't parsed

- src/dpp/message.cpp
One could not apply `min_values`, `max_values` or `placeholder` fields on the new select menu types earlier, this PR should resolve that.
_Btw idk if there are other functions that need this, I just fixed the ones that I normally use._
> Add missing fields for new select menu types

- src/dpp/sslclient.cpp
ssl client has
```c
1:  if (last_tick != time(nullptr)) {
2:    this->one_second_timer();
3:    last_tick = time(nullptr);
4:  }
```
The problem is, is that the time could change between the condition on line 1, and setting it on line 3. This can't be changed, as it would cause bugs in other places. The poll syscall further down can be reworked to wake up at the beginning of the second to make it less likely for the time difference on lines 1, and 3 to occur. Other parts of the code rely on specific times to operate, and they may be skipped over regardless, this just makes it far less likely to occur.
I'm aware, that sslclient is running on its own thread, and there may be many running, it might be best to stagger the wake up at a random interval `(beginning of second + rand(0 to 100) …
> Stabilize Tick Rate in sslclient

- src/dpp/events/ready.cpp
- src/dpp/integration.cpp
- src/dpp/message.cpp
- src/dpp/presence.cpp
- src/dpp/slashcommand.cpp
This PR fixes a few issues when building in C++23 mode using GCC.
- One instance of undefined behaviour with `std::string` which now correctly causes a compile error
- A few ambiguous conversions from json objects to strings
> Fixed various C++23 issues

- docpages/02_building_a_bot.md
- docpages/example_programs/interactions_and_components/modal_dialog_interactions.md
- docpages/make_a_bot/meson.md
Instructions to writing a bot in meson.
> Add meson instructions to docs.

- cmake/FindSodium.cmake
Related to #545. Not sure if this is just a Debian related issue (or any distro without pkg-config installed by default), but not silencing `find_package` output should help spot the issue earlier if someone else runs into this.
> Print status message from find_package(PkgConfig)

- library-vcpkg/CMakeLists.txt
Dpp was being built without voice support with vcpkg
> fix voice support for vcpkg

- docpages/example_programs/misc/eval.md
Line 175 was ended with a , instead of a ;
> Fix missing semicolon in example

- src/dpp/user.cpp
Reverts brainboxdotcc/DPP#561
doesn't fix anything just breaks all the flags. not tested.
> Revert "fix(issue #560): The bot does not return the entire user badge."

- src/dpp/cluster/confirmation.cpp
While toying around, I got the following discord api error:
```json
{
"code": 50035,
"errors": {
"options": {
"0": {
"_errors": [
{
"code": "UNION_TYPE_CHOICES",
"message": "Value of field \"type\" must be one of (3, 7, 10, 4, 5, 11, 6, 8, 9, 1, 2)."
}
]
}
}
},
"message": "Invalid Form Body"
}
```
Which throws an exception because dpp expects the '_errors' array to be in an intermediate 'field' object.
This PR fixes that.
> fix: array of error parsing

- src/dpp/cluster/thread.cpp
- src/unittest/test.cpp
> fix: dpp::cluster::thread_create_in_forum() crashes the bot without a clear error when the bot has insufficient permissions (#577)

- .cspell.json
- include/dpp/application.h
- include/dpp/cluster.h
- include/dpp/restrequest.h
- include/dpp/restresults.h
- include/dpp/role.h
- src/dpp/application.cpp
- src/dpp/cluster/role.cpp
- src/dpp/role.cpp
Only tested `application_role_connection_get` and `application_role_connection_get`. Couldn't test the others yet.
> feat: added support for application role connection metadata

- cmake/CPackSetup.cmake
- cmake/libdpp-config.cmake
This PR contains fixes for the CMake installation on Linux, removing redundant dirs, fixing `include()` statements and adhering to standard system directories, thus allowing reverse dependencies to find this package easily without any special configuration.
Note: These are the same fixes used in a Gentoo ebuild I use locally on my systems to install DPP. A similar set of patches (although not in the form of patch files) is applied in the AUR to make the package work. Thus, we have proof of concept that this patchset does what it should.
Closes: #590
> Fixes to the DPP installlation on Linux

- include/dpp/dispatcher.h
- src/dpp/dispatcher.cpp
Instead of overwriting the inherited get_parameter method in classes who doesn't have parameters, we can just make it private.
> refactor: removed code redundancy by get_parameter and make it private instead of overwriting it

- include/dpp/cluster.h
Having the typedef inside the global namespace will give an overshadowing error if any `using json=...` statement is used.
> Moved json typedef inside the namespace

- include/dpp/automod.h
- include/dpp/dispatcher.h
- include/dpp/message.h
- src/dpp/automod.cpp
- src/dpp/channel.cpp
tested with the following code:
```c++
dpp::automod_rule rule;
rule.trigger_type = dpp::amod_type_mention_spam;
dpp::automod_metadata metadata;
metadata.mention_total_limit = 12;
rule.trigger_metadata = metadata;
rule.name = "Very fast detection";
dpp::automod_action action1;
action1.type = dpp::automod_action_type::amod_action_block_message;
action1.custom_message = "Too many mentions in your message :(";
dpp::automod_action action2;
action2.type = dpp::automod_action_type::amod_action_timeout;
action2.duration_seconds = 3600;
dpp::automod_action action3;
action3.type = dpp::automod_action_type::amod_action_send_alert;
action3.channel_id = 845266178036596767;
rule.actions.push_back(action1);
rule.actions.push_back(action2);
rule.actions.push_back(action3); …
```
> feat: Added custom message for automod rules

- src/dpp/discordclient.cpp
Trying to pass intents as 0 would throw a websocket error:
```
[Mon Feb 27 06:28:47 2023] WARN: OOF! Error from underlying websocket: 4013: Invalid intent(s)
```
This PR fixes that. (Thanks @eirk#7057 for helping find the root cause)
> Fix WS error when intents is 0

- docpages/01_installing.md
- docpages/install/install-clion.md
- docpages/install/install-windows-clion-vcpkg.md
- docpages/install/install-windows-vs-zip.md
Clear instructions on how to set up the D++ library by installation through vcpkg and then updating CLion project settings and CMakeLists.txt
Tested for ping/pong bot
> Documentation for setting up D++ in CLion with CMake and vcpkg

- include/dpp/cluster.h
- include/dpp/httpsclient.h
- include/dpp/message.h
- include/dpp/queues.h
- src/dpp/cluster.cpp
- src/dpp/cluster/appcommand.cpp
- src/dpp/cluster/message.cpp
- src/dpp/cluster/sticker.cpp
- src/dpp/cluster/thread.cpp
- src/dpp/cluster/webhook.cpp
- src/dpp/dispatcher.cpp
- src/dpp/httpsclient.cpp
- src/dpp/message.cpp
- src/dpp/queues.cpp
- src/unittest/test.cpp
As I found out the hard way on my bot [B-12](https://github.com/Mishura4/B-12) while adding a command to add stickers, it turns out the sticker create API expects the file it receives to have a MIME type that corresponds to its data. I spent hours trying to troubleshoot my bot's code, but while digging into DPP code it became clear that the `application/octet-stream` MIME type it sent by default was what was causing the issue, as changing it to `image/png` allowed it to be accepted by the API.
This pull request adds MIME types to APIs that deal with raw file uploading through the REST API. This includes data members in `dpp::http_request`, in `dpp::message`, and function signature changes. MIME type defaults to `application/octet-stream` if unspecified by the user.
This effectively :
- …
> fix, feat: Add MIME type to HTTP file transfer API

- src/dpp/slashcommand.cpp
The issue is that commands received from discord wasn't fully parsed when the command had too many subcommands, subcommand groups and options in general.
> fixed command_option parsing which didn't parse commands with too many subcommands and subcommand groups

- src/dpp/queues.cpp
See context [from the D++ discord server](https://discord.com/channels/825407338755653642/825411707521728512/1095776446196228237)
> fix: add missing mimetype to external HTTPS requests

- include/dpp/stringops.h
- src/dpp/discordvoiceclient.cpp
- src/dpp/sslclient.cpp
Using a MacOS 13.2 with Xcode 14.2 I received the following warnings. 
Implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int')
Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int'
Added casts solved the warnings and is still consistent with the intention of the code.
> added explicit casting to avoid warnings

- include/dpp/auditlog.h
- include/dpp/cluster.h
- include/dpp/dispatcher.h
- include/dpp/event.h
- src/dpp/auditlog.cpp
- src/dpp/discordevents.cpp
- src/dpp/dispatcher.cpp
- src/dpp/events/guild_audit_log_entry_create.cpp
This PR implements the missing Guild Audit Log Entry Create gateway event.
Reference: https://discord.com/developers/docs/topics/gateway-events#guild-audit-log-entry-create
Tested simply using
```c++
bot.on_guild_audit_log_entry_create([](const dpp::guild_audit_log_entry_create_t &event) {
std::cout << "audit log entry received; reason: " << event.entry.reason << " , user_id: " << event.entry.user_id << " , type: " << to_string(event.entry.type) << std::endl;
});
```
> feat: added on_guild_audit_log_entry_create gateway event

- include/dpp/guild.h
- src/dpp/guild.cpp
Reference: https://github.com/discord/discord-api-docs/commit/c38ca4d817cde888c1a3d601aed98ffcea2a154a
**This PR bumps the guild member flags from `uint8_t` to `uint16_t`**!
Added The 4 missing guild member flags. Added a setter for the BYPASSES_VERIFICATION flag and getter for all 4. Haven't tested to edit a guild member with the new flags btw.
> feat: added guild member flags

- include/dpp/permissions.h
- src/dpp/permissions.cpp
- src/unittest/test.cpp
This PR modernizes dpp::permission by making it constexpr-compatible, making use of C++17 features and common practices.
Notable changes :
- Made value data member public, changed class to struct
- Made member functions constexpr and noexcept (except for conversion to json which may throw)
- Added unit tests for it
This effectively allows for a user to declare constexpr variables with the type `dpp::permission`, allowing to make use of the class's convenience member functions. As the type is effectively a convenience wrapper around the enum `dpp::permissions`, it allows to be used as an extension of it in a constexpr context, this is useful for example if a user wants to make a constexpr command table with default permissions, it allows them to use the dpp::permission convenience methods …
> refactor: modernize dpp::permission

- include/dpp/discordclient.h
- src/dpp/discordclient.cpp
dpp::discord_voice_client does not free its active voice connections on destruction. This means that, when the cluster/voice client gets destroyed, any dpp::voiceconn objects as well as threads they have running won't be joined or freed. This causes not only a memory leak, but in the event of the cluster/voice client getting destroyed, and the still alive voiceconn thread trying to for example log a message, a use-after-free will occur and cause undefined behavior (usually a crash). This has happened to me about on about 50% of my executions of the unit tests on Windows.
This PR fixes this bug. However it does make use of std::unique_ptr, that as I understand it the library does not usually use, let me know if you would like me to change it to new/delete instead.
> fix: fixed memory leak and potential use-after-free bug with voiceconn

- src/unittest/test.cpp
This fixes start_timer and message_collector tests failing due to the shard thread being blocked
> test: refactor blocking calls out from events in unit tests

- include/dpp/user.h
- src/dpp/user.cpp
https://discord.com/developers/docs/resources/user#users-resource 
Users can now set a global_name, and since the Dev docs now tell us we can expect it in the user object we should add it to dpp::user
> feat: Added global_name to dpp::user

- src/dpp/user.cpp
Update dpp::user::get_default_avatar() to also work with new username system (see ** under https://discord.com/developers/docs/reference#image-formatting)
> Fix: Adapt dpp::user::get_default_avatar() to new username system 

- library-vcpkg/CMakeLists.txt
Hello everyone 👋 
Using DPP with vcpkg and CMake on Windows seems to create some trouble when it comes to compiler definitions. They look like they are compiler options, not definitions.
Moving them fixes an annoying intellisense error in Visual Studio (`command-line error: invalid macro definition: /sdl`) - atleast inside the auto-generated cmake-file (share-dir).
Sadly I can't test these changes on my own, I am completly new to vcpkg.
Additionally I thought it would make more sense to remove the /DEBUG-Option for everything but Debug builds, I don't really see a point for this option if we build Release - it will be tested in Debug anyway, right? Feel free to correct me.
Possible fix for #710
> [vcpkg] Move misplaced compiler definitions to options and make linker option Debug-Mode dependent

- include/dpp/stringops.h
Title. This notably fixes HTTP multipart requests failing if locale is set to something else globally, due to form hex boundaries having for example commas in them, making them ill-formed. (see [src/dpp/httpsclient.cpp:86](https://github.com/brainboxdotcc/DPP/blob/a822694ed6b1a103a3fc09bcf495059d60997796/src/dpp/httpsclient.cpp#L86))
> fix: force dpp::to_hex to use std::locale::classic for formatting

- src/unittest/test.cpp
- src/unittest/test.h
- src/unittest/unittest.cpp
Title. Moved some online tests into an optional, off by default set. Run with "full" command argument to run the full online set.
Also added a "TIMEOUT" notification for any remaining tests when the tests are killed and changed INVITE_GET to not rely on permanent invites, as [Discord has disabled permanent invites for non-community servers](https://support.discord.com/hc/en-us/articles/208866998-Invites-101#h_01H2DMMG355MV7GJDQ9F65SDVG).
> test: add extended unit tests mode

- include/dpp/coro.h
- library/CMakeLists.txt
This PR should improve compiler support for coroutines. Mainly, it adds clang with stdc++, as well as clang17, which removed experimental headers.
The list of supported compilers becomes as follows :
- g++: experimental support for g++10 (requires `-fcoroutines` on a consumer project), native support from g++11 onwards
- clang:
- [9, 14): experimental support with libc++
- [12, 14): experimental support with stdc++/glibcxx
- 14+: native support with either
- no changes for MSVC (still "17.something")
Draft, I still need to test compilers.
> fix: coroutines: better support for clang, remove experimental if unneeded, add missing headers

- include/dpp/appcommand.h
- src/dpp/cluster/appcommand.cpp
- src/dpp/slashcommand.cpp
Fixes double free on copy of interaction_response, for example capturing it by copy in a lambda.
All full suite of tests passed on g++12.
> Failed: 0 Passed: 140 Percentage: 100.00%
> refactor, fix: change interaction_response.msg from message* to message, fixing double free on copy

- .github/workflows/codeql.yml
Improved codeql speed, remove autobuild
Tested four different approaches to compiling D++ for analysis by codeql:
* CodeQL `Autobuild` (default): 1 hour, 11 mins, 30 secs
* `ninja` Build: 45 mins (including 1 minute apt install step to install `ninja-build`)
* `make -j4`: 41 mins, 1 sec
* `make -j2`: 30 mins 30 secs
I selected `make -j2`, this should ensure that codeql completes in under an hour including its analysis step and is a bit more tolerable.
> docs: improve build speed of codeql

- buildtools/changelog.php
- Added the ability for the parser to parse more patterns :
- A commit with several categories, e.g. `foo, bar: many foos, many bars`. Only the first category is taken into account, but all of them are split and parsed with a regex, so they can easily be used if needed. ❗ Commits marked as breaking will always be listed at the top the changelog in the breaking section (alongside their own category if the breaking was a secondary category)
- A commit with a scope, e.g. `feat(scope): some changes`, all commits with the same scope will be grouped together in the changelog, listed as `Scope: some changes`
- Fixed the order of the categories, which are now listed in declaration order, as opposed to in the order of the first commit that references them
- The script will warn if a commit has …
> build: improve changelog parsing and order

- include/dpp/emoji.h
- include/dpp/utility.h
- src/dpp/cluster/sticker.cpp
- src/dpp/discordevents.cpp
- src/dpp/emoji.cpp
- src/dpp/utility.cpp
- src/unittest/test.cpp
- src/unittest/unittest.cpp
- [✅] My pull request is made against the `dev` branch.
- [❓ github actions will tell :kekw:] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [✅] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [✅] I tested my commits, by adding a test case to the unit tests if needed
- [✅] I have ensured that I did not break any existing API calls.
- [✅] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [✅] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request …
> fix: fix various issues and bugs with dpp::emoji

- include/dpp/cluster.h
- src/dpp/cluster.cpp
> fix: don't allow user to change ws mode on a connected cluster (this would be bad)

- docpages/example_programs/misc/collect_reactions.md
Replaced the message_collector template in the constructors with reaction_collector as the previous one was wrong, and would introduce an error.
I have also replaced list[0].channel_id with list[0].react_channel->id, as channel_id object does not exist.
> docs: fixed errors on reaction collectors example page

- include/dpp/cluster.h
- src/dpp/cluster.cpp
Default PR checklist doesn't apply, changes made to documentation.
> docs: fixed typo in documentation example

- docpages/example_programs/misc/collect_reactions.md
collect_reactions never used "override" with virtual void completed(), this changes that. Whilst it's not needed, it's better to be explicit.
This also clears the random indentation on line 36 (prev. line 29).
> docs: Made collect_reactions page more explicit.

- CMakeLists.txt
- library/CMakeLists.txt
Adds an option to use private PCH when building DPP from source.
Mostly useful on MSVC, makes the build take 30 seconds instead of 5 minutes.
Useful for contributors mostly 👀 as this only affects DPP itself due to being private, and does not propagate to dependents.
This does not affect vcpkg.
> feat(build): add off-by-default DPP_USE_PCH option in CMake

- docpages/advanced_reference/automating-with-jenkins.md
This PR improves the automating-with-jenkins.md page, adding a note about threading the CMake build process, improving some wording here and there and adding a warning in the `Running the build` section as previously there was no communication to tell people to move builds away from Jenkins if their bot will be up whilst Jenkins is building (now communicating a better practice of automating builds)
> docs: improved Jenkins page.

- docpages/advanced_reference/coroutines.md
- include/dpp/event_router.h
- include/dpp/utility.h
- src/unittest/coro.cpp
- src/unittest/test.cpp
[Context](https://discord.com/channels/825407338755653642/1018812514139635712/1144668064361742436) (accessible to reviewers)
For non-reviewers, the tl;dr is `std::function` does very little to enforce call semantics such as a return type.
This PR actually enforces the call semantics using type traits. It also removes co_attach and now unifies usage for coro / non coro event handlers (you attach a coro event handler using `attach` or `operator()`).
> break: remove co_attach & enforce event handler call semantics (return void/dpp::job, take const event)

- .cspell.json
- include/dpp/coro.h
- include/dpp/coro/coro.h
- include/dpp/coro/coroutine.h
- include/dpp/coro/job.h
- include/dpp/coro/when_any.h
- include/dpp/event_router.h
- include/dpp/export.h
- include/dpp/utility.h
> feat(coro): more stuff! not breaking this time!

- buildtools/changelog.php
> ci: silence changelog generator warning emission, not useful when running by hand

- include/dpp/permissions.h
- include/dpp/role.h
- src/dpp/role.cpp
Implements https://github.com/discord/discord-api-docs/pull/6354
> Implement clyde AI permission bits

- library-vcpkg/CMakeLists.txt
This is applied to the v10.0.25 release in vcpkg via a patch. We do not need to push any kind of hotfix
> fix: vcpkg wouldnt build

- library-vcpkg/CMakeLists.txt
this fixes warnings when building vcpkg with msvc. I'll submit a more in depth tidy up when I have facility to test it properly without having to wait until a vcpkg pr.
> Remove bad compile defs

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
- Fix `send_audio_raw` blocking thread when provided with invalid size
- Define `SEND_AUDIO_RAW_MAX_LENGTH` so users can choose not to hardcode the size in their code
- Update comment
> fix: fixed discord_voice_client::send_audio_raw blocking thread when provided with invalid size

- .gitignore
- src/dpp/presence.cpp
This PR changes presence.cpp to allow custom statuses. The way discord asks for a presence means we need to set the "state" in the json object, however, we don't do this (hence this PR!). This now means you can do the following:
```
bot.set_presence(dpp::presence(dpp::presence_status::ps_online, dpp::activity_type::at_custom, "Testing 123!"));
```
This PR also adds "cmake-build-debug" to the `.gitignore`.
I also have no idea why the indentation is weird, I simply added the code in CLion and it looks great on my end, but on GitHub and a text editor it does that. If it's okay to leave then that's great, otherwise, I'm happy for someone to give me a fix for it!
> fix: corrected presence.cpp to allow custom statuses.

- docpages/install/install-vcpkg.md
This PR modified the `install-vcpkg.md` page so that it no longer indicates that it works for Linux and OSX. It also now contains a notice to state that we no longer fully support VCPKG properly (still maintaining and updating, but not testing).
This PR also merges some changes from #820.
> docs: refactored install-vcpkg.md

- docpages/06_advanced_reference.md
- docpages/advanced_reference/coding_style_standards.md
This PR merges `coding_style_standards.md` with #820. This is because, previously, the coding standards were slightly incorrect and needed fixing (as requested by Brain).
> docs: merged coding_style_standards.md with #820

- include/dpp/collector.h
- include/dpp/json_interface.h
- include/dpp/timed_listener.h
- [*] My pull request is made against the `dev` branch.
- [*] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [*] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [*] I tested my commits, by adding a test case to the unit tests if needed
- [*] I have ensured that I did not break any existing API calls.
- [?] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [*] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request using a tool, I have justified why …
> added [[maybe_unused]] in some places where it was needed

- .github/workflows/ci.yml
- cmake/ARM64ToolChain.cmake
- cmake/ARMv7ToolChain.cmake
- src/unittest/test.h
> ci: remove ninja for all but windows, for us it is slower than make -j2

- include/dpp/isa_detection.h
- src/dpp/wsclient.cpp
As it makes sense to have them as constexpr.
> Updating some variables to be constexpr.

- .github/PULL_REQUEST_TEMPLATE/code_change_template.md
- .github/PULL_REQUEST_TEMPLATE/docs_change_template.md
This PR adds missing punctuation from #868, and fixes a spelling mistake in the second bullet point (changing `oxygen` to `doxygen`, the fix can be seen below).
> refactor: changed templates to properly fix changes from #868

- include/dpp/discordvoiceclient.h
discordvoiceclient.h was not referencing `dpp::cluster::on_voice_buffer_send` correctly, this has been altered. I've also changed the notice of `the audio data needs to be...` to be a warning, to which it also states that the audio will be affected if it isn't at that hz (just to inform people what will happen otherwise).
> docs: fixed a ref issue and added more info in discordvoiceclient.h

- cmake/DetectArchitecture.cmake
Fixing the AVX2 detection instruction.
> Fix: Fixing the AVX2 detection instruction.

- cmake/DetectArchitecture.cmake
- include/dpp/isa/avx.h
> Fix: Fixing a typod type in avx.h

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR adds the [labeler action](https://github.com/marketplace/actions/labeler) (spelling is different due to US) to PRs, automatically assigning the documentation label when any files listed in `.github/labeler.yml` are changes. I included any header file in this as, if people are adding new content, they should be documenting it. Of course, we could always alter this if wanted or just remove the label if it's not applicable (but this will cover most bases).
[This was tested on my fork and works perfectly.](https://github.com/Jaskowicz1/DPP/pull/6)
Neither checklist applies here, this is why the changelist does not include a checklist.
> feat: added an auto-labeller for documentation PRs.

- src/dpp/discordevents.cpp
This PR fixes #765, stopping "_XOPEN_SOURCE" from compiling on OpenBSD. This has been tested and is fully working on OpenBSD. I have tested this fix on Ubuntu 22.04 and WSL and they can still compile and run sucessfully.
> fix: stopped _XOPEN_SOURCE from defining on OpenBSD

- docpages/06_advanced_reference.md
- docpages/advanced_reference/voice_model.md
This PR adds the big voice graph that I made and showed on discord (with changes). Brain thought it would be cool so here we are :)
> docs: added a voice model page

- include/dpp/stringops.h
> fix: awful wrong indentation in stringops

- include/dpp/discordvoiceclient.h
- include/dpp/isa/avx.h
- include/dpp/isa/avx2.h
- include/dpp/isa/avx512.h
- src/dpp/discordvoiceclient.cpp
Storing it along with the array of floats that are used as an intermediary for converting to/from avx registers seems to cut down CPU usage while streaming audio in my implementation by roughly 50%. As opposed to reallocating the array for every function call.
> Enhancement: Making AudioMixer a member instead of invoking it statically to cut down CPU usage by roughly 50%

- docpages/building/02_build.md
- docpages/building/openbsd.md
This PR adds a page for building D++ on OpenBSD. The guide has been followed on a fresh install of OpenBSD and a fresh install of D++ (latest master) and works.
> docs: added an openbsd page

- include/dpp/etf.h
- src/dpp/etf.cpp
This removes two instances of type punning in the ETF parser. Please take note of the comments added to the function `etf_parser::process_atom()`. This is a performance hotspot and any changes to this function should be carefully profiled.
> refactor: destroy spawn of satan type punning in ETF parser

- docpages/example_code/coro_simple_commands2.cpp
- docpages/example_code/join_voice.cpp
- docpages/example_code/oggopus.cpp
- src/dpp/channel.cpp
- src/dpp/cluster.cpp
- src/dpp/discordvoiceclient.cpp
- src/dpp/emoji.cpp
- src/dpp/etf.cpp
- src/dpp/events/voice_state_update.cpp
- src/dpp/guild.cpp
- src/dpp/integration.cpp
- src/dpp/invite.cpp
- src/dpp/message.cpp
- src/dpp/presence.cpp
- src/dpp/queues.cpp
- src/dpp/slashcommand.cpp
- src/dpp/sslclient.cpp
- src/dpp/utility.cpp
- src/dpp/voiceregion.cpp
- src/dpp/voicestate.cpp
- src/dpp/webhook.cpp
- src/dpp/wsclient.cpp
- src/unittest/coro.cpp
- src/unittest/test.cpp
- src/unittest/unittest.cpp
This fixes instances where `if` has no space between itself and its bracket, or has no braces around a single statement associated with it, or its `else`, or has braces on the next line. This goes against the code style guide. Also fixed a few for() i noticed along the way etc, but didnt go out of my way to find other stuff. We will fix that "`if` and when we find it". LOL programmer pun.
> style: fix some simple style issues that seem to happen a lot

- include/dpp/utility.h
This PR alters the notes on `dpp::utility::read_file`. After experimenting in DPP-UE, I realised that there was no note as to what happens if the file is big and causes the event to timeout, causing a crash in DPP-UE and an error log in DPP. I made the note to give more information to users about this, making sure they know to use `thinking` if the file is big.
The PR also renames the previous note to be a warning. I feel that the warning is very much required so people know that the function can, and will, block the thread, if the file is big.
> docs: changed the notes on read_file.

- src/dpp/wsclient.cpp
> fix: should fix #714, closes out issue where length of websocket-sec-key was wrong

- src/dpp/sslclient.cpp
- src/dpp/wsclient.cpp
The code added in a previous PR would cause unceccessary checks of the data every time we did SSL_read, this really belongs in wsclient when looking for the 101 reply, so i moved it.
> move the error checks from sslclient.cpp to wsclient.cpp where they belong, so they dont cause excessive data copies or false alarms

- .github/labeler.yml
- .github/workflows/ci.yml
- .github/workflows/construct-vcpkg-info.yml
- .github/workflows/docker.yml
- .github/workflows/documentation-check.yml
- .github/workflows/documentation.yml
- .github/workflows/gitguardian.yml
- .github/workflows/labeler.yml
- .github/workflows/sitemap.yml
- .github/workflows/stale.yml
- .github/workflows/target-master.yml
- .github/workflows/test-docs-examples.yml
This PR changes the security on the workflows to follow [GitHub's security workflow for permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions). This PR does not change the following pages:
- ci.yml (not enough information nor testing to see if this will work)
- codeql.yml (permissions already exist here)
- dependency-review.yml (permissions already exist here)
- scorecard.yml (permissions already exist here)
> ci: Improved security on workflows.

- README.md
> docs: added OpenBSD to readme

- include/dpp/guild.h
- src/dpp/guild.cpp
- src/dpp/role.cpp
- src/unittest/coro.cpp
- src/unittest/test.h
You must now use add_role, remove_role or set_roles, also set_nickname on a guild_member for edit_guild_mebmer to have any effect on that value. This fixes longstanding issue where more permissions are required than should be, to edit guild members
> breaking, fix: guild_member state tracking

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/documentation.yml
- .github/workflows/gitguardian.yml
https://github.com/orgs/community/discussions/53506
https://www.polpiella.dev/cancelling-unnecessary-github-actions-automatically/
Values for cancel concurrent swapped over, so that PRs dont all stack up crazy-like.
> ci: prevent ci runs being cancelled by github incorrectly (backwards)

- src/dpp/guild.cpp
Guild member flags cannot be set by a bot. They are set by a user in the client. Sending them causes permission denied. The deaf/muted settings are separate and sent as individual bools in the json, and can be set by a bot.
In fact, the flags that this would set, we don't even have set_ methods for.
> fix: guild member flags can't be set by a bot

- docpages/building/freebsd.md
- docpages/building/openbsd.md
This PR corrects the freebsd.md page, so it now works with `clang++` as found from #901. It also corrects openbsd.md, so it no longer states that `clang++` works for OpenBSD, but rather states it can only be used with CMake.
I've also merged changes from #820 into this PR.
> docs: corrected freebsd.md and openbsd.md

- .github/workflows/labeler.yml
Fixed an issue where labeler was failing due to a permissions issue. This was caused by #913.
The checklist does not apply.
> ci: fixed an issue with labeler failing

- docpages/make_a_bot/windows_vs.md
This PR changes the link to a video in windows_vs.md to now be embedded in the page.
> docs: embedded video into windows_vs.md

- src/dpp/slashcommand.cpp
This PR adds an error message into the constructor of `command_option`. This is just to make it more user-friendly for people, rather than discord just returning an error.
> feat: added an error for caps in command_option.

- .vscode/settings.json
- include/dpp/restresults.h
- src/dpp/cluster/confirmation.cpp
- src/dpp/utility.cpp
- src/unittest/test.cpp
- src/unittest/test.h
turns out the parser for error objects wasnt far off anyway, just needed to keep track of indicies.
> feat: improved human readable error messages to default logger, with unit test

- include/dpp/utility.h
- src/dpp/utility.cpp
feat: added support for hsl colors to be used in embed
> feat: added support for hsl colors

- include/dpp/discordevents.h
- src/dpp/discordevents.cpp
Surely this will save more than a couple seconds of build
> build: refactor json.h out of include from discordevents.h

- src/dpp/discordevents.cpp
```
UNIT TEST SUMMARY
==================
Instantiate DPP cluster                                      PASS
cluster::start method                                        PASS
Connection to client websocket                               PASS
Creation of application command                              PASS
Deletion of application command                              PASS
Log events                                                   PASS
Creation of a channel message                                PASS
Editing a channel message                                    PASS
Message edit event                                           PASS
Deletion of a channel message                                PASS
Receipt of a created message                                 PASS
Message attachment send and …
```
> fix: fix bug introduced by #927

- src/dpp/channel.cpp
This PR fixes an issue with threads, as they weren't sending correctly to discord [according to this part of the documentation](https://discord.com/developers/docs/resources/channel#:~:text=json%20params%20(thread)). This means threads can now be locked and archived correctly.
> fix: threads now send correctly to discord.

- .github/workflows/ci.yml
Adds clang 10-15 to CI and bumps up concurrency on macos from 2 to 3.
clang++ 15 has CORO, 10-14 do not, to test a wide range of configurations.
> CI: add clang builds

- include/dpp/cluster.h
- include/dpp/cluster_coro_calls.h
- include/dpp/cluster_sync_calls.h
- src/dpp/cluster/appcommand.cpp
- src/dpp/cluster_coro_calls.cpp
- src/dpp/cluster_sync_calls.cpp
This PR adds a function, allowing you to delete all your global/guild registered commands.
> feat: added bulk command deleting.

- docpages/example_code/clearing_slashcommands.cpp
- docpages/example_programs/interactions_and_components.md
- docpages/example_programs/interactions_and_components/clearing_slashcommands.md
This PR adds a page about clearing commands, which is added by #938 .
> docs: added a page for clearing slashcommands

- include/dpp/snowflake.h
Updating libfmt to v10 for my bot broke `fmt::format("{}", dpp::snowflake{})`, this makes it work again
> fix: make snowflake formattable again

- src/dpp/message.cpp
In the event all caches are disabled, roles list in the member for a message was empty. This was because it was internally using find_guild and skipping this part of the deserialisation. It does not need to do this. This fix ensures that if all caching is off, and we have the guild members intent, the guild member list in the messages member field will be popupated. I'm relying on this in the yeet bot.
> fix: dont require guild cache to fill member roles in message

- include/dpp/cluster.h
- include/dpp/httpsclient.h
- include/dpp/queues.h
- src/dpp/cluster.cpp
- src/dpp/httpsclient.cpp
- src/dpp/queues.cpp
Adds optional parameter to dpp::cluster::request(). This is a non-breaking change, the default is still 1.1. This is required for some braindead api's im working with in DPP, so if i'm having this problem others could too. This offers a workaround, which is there if others want to use it.
> feat: allow changing of HTTP protocol to 1.0 for backwards API endpoints and broken servers

- include/dpp/application.h
- include/dpp/discordevents.h
- src/dpp/application.cpp
- src/dpp/discordevents.cpp
This PR now updates dpp::application, making it up-to-date (and even have content discord doesn't document yet). It also adds `set_iconhash_not_null`, meaning we don't have to do workarounds to set the iconhash as it can be set from a string.
> feat: dpp::application is now updated, added set_iconhash_not_null

- include/dpp/integration.h
- src/dpp/integration.cpp
This PR updates integration according to [this page in the documentation](https://discord.com/developers/docs/resources/guild#integration-object). This may also be a breaking change as I removed a deprecated feature, along with changing `account_name` and `account_id` to a struct.
This PR also severely changes the documentation for many variables in this, as it never stated before which variables would **not** appear for a bot. It also just missing documentation that discord was providing.
> feat!: updated integration to now contain more information

- docpages/example_programs/misc/setting_status.md
This PR adds a note to `setting_status.md` about the guild cache, telling people how they can still display a guild count without the guild cache on (if they wish to do so). I'm not entirely sure if you can safely call the two methods I provided every 120 seconds without getting rate-limited, so if there's a better method then please do say!
> docs: added a note to setting_status for guild cache

- include/dpp/message.h
- src/dpp/message.cpp
made `embed::color` a `std::optional`
Discord does not use `0x000000` as the default embed color, so this actually does result in a visual change to the embeds created that dont have a color, (also has a more noticable change in light mode)
Before:
After:
> fix: make embed color optional

- src/dpp/events/interaction_create.cpp
Before, subcommand autocomplete wasn't parsed properly. Now, it has been fixed.
Notably, it requires a recursive lambda.
I tested this, and it works for subcommands. Not sure if it works for subcommand groups w/ subcommands.
> feat: support subcommand autocomplete

- include/dpp/emoji.h
- src/dpp/cluster/emoji.cpp
- src/dpp/emoji.cpp
This PR adds roles to emojis, allowing bots to restrict emojis to certain roles. You can view discord's documentation about this at [this page](https://discord.com/developers/docs/resources/emoji#emoji-object).
This also changes how we store the user, along with how we send information to discord. We now store the actual user object rather than a user_id (as discord provides the user object, this helps people who may not have cache on so they don't have to make another API request to get the user).
The information above is a breaking change.
> feat: added roles to emojis

- include/dpp/webhook.h
- src/dpp/cluster/webhook.cpp
- src/dpp/webhook.cpp
This PR adds a new webhook type called `application`, as specified by [the discord documentation](https://discord.com/developers/docs/resources/webhook#webhook-object). It also now supports data from webhooks that Channel Follower Webhooks, as previously we didn't take in the `source_guild`, and `source_channel` data.
I've also changed user to be a user object.
> feat: added application and following support for webhooks.

- src/unittest/test.cpp
> fix, test: multiheader-cookie test, now queries a domain and url in our control which returns 3 hard coded test cookies                         

- include/dpp/restresults.h
This PR wraps the version checker in an if statement, checking if any UE definitions are declared. This means Unreal Engine will no longer constantly break with the version checker.
> feat: removed version_checker for UE.

- include/dpp/emoji.h
- include/dpp/guild.h
- include/dpp/role.h
- include/dpp/scheduled_event.h
- include/dpp/user.h
- include/dpp/utility.h
- src/dpp/emoji.cpp
- src/dpp/guild.cpp
- src/dpp/role.cpp
- src/dpp/scheduled_event.cpp
- src/dpp/utility.cpp
- src/unittest/test.cpp
- src/unittest/test.h
- src/unittest/unittest.cpp
WIP fix for #957 
Do not squash
> fix(#957): support iconhash/image data variant fields

- include/dpp/appcommand.h
- include/dpp/application.h
- include/dpp/automod.h
- include/dpp/ban.h
- include/dpp/cache.h
- include/dpp/coro/async.h
- include/dpp/coro/coro.h
- include/dpp/coro/coroutine.h
- include/dpp/coro/job.h
- include/dpp/coro/task.h
- include/dpp/coro/when_any.h
- include/dpp/sku.h
- include/dpp/wsclient.h
This PR refactors several files to follow the comments standard, as we discussed in Discord that many files didn't (they were doing `//!<` or `///`).
> style: refactored comments in several files to follow standard

- include/dpp/emoji.h
- include/dpp/message.h
This PR removed `inner_select_emoji` from `select_menu` and renames `inner_emoji` to `component_emoji`. `select_menu` now uses `component_emoji`.
> refactor: renamed inner_emoji, changed select_menu and component to use it.

- include/dpp/cluster.h
- include/dpp/export.h
- include/dpp/restresults.h
- src/dpp/cluster.cpp
Please go the the `Preview` tab and select the appropriate pull request template for your changes:
* [Code Changes](?expand=1&template=code_change_template.md)
* [Documentation Changes](?expand=1&template=docs_change_template.md)
> fix: exorcised the scary head. halloween is over

- .github/workflows/ci.yml
Changes the CI to use a native arm7 self-hosted runner. This is hosted on a raspberry pi 4B.
The scripts for anyone to do this if needed are [available here](https://github.com/brainboxdotcc/self-hosted-runner) if anyone else has the desire to set up a similar self-hosted runner which we could use in the future. The self-hosted runner scripts support arm, arm64, amd64.
> ci: add self hosted arm runner

- src/dpp/cluster.cpp
> fix: add maybe_unused to build_type constexpr to squash warning

- src/dpp/events/interaction_create.cpp
- src/dpp/slashcommand.cpp
This PR fixes #962, checking if a value from an autocomplete is actually what we expect it to be, rather than unsafely assuming. This caused a crash because discord sends `""` upon `on_autocomplete` (no data), however, because the type is int, it can't convert to int so it throws instead. This no longer happens and we now just don't bother with the set if the type doesn't match.
> fix: integer autocompletes no longer cause crash

- .github/workflows/ci.yml
ARM64 is no longer a cross-compile. It is a self-hosted runner in a docker container at Hetzner running on Ampere. It compiles DPP in 3 mins 🚀
> ci: move arm64 to self hosted runner

- include/dpp/cluster.h
- include/dpp/message.h
- src/dpp/cluster.cpp
- src/dpp/cluster/appcommand.cpp
- src/dpp/cluster/message.cpp
- src/dpp/cluster/thread.cpp
- src/dpp/cluster/webhook.cpp
- src/dpp/dispatcher.cpp
- src/dpp/message.cpp
This PR changes the way that messages hold files. Rather than there being 3 vectors of strings for: name, content and mimetypes, there is now a vector of `message_file_data` structs.
This doesn't break the way you add files, but rather breaks the way you read files you've added to a message.
> refactor: changed the way messages holds files

- include/dpp/voiceregion.h
- src/dpp/voiceregion.cpp
This PR fixes voiceregion, now filling it from json correctly. It also removes `VIP` from voiceregion as that was removed a while ago and replaced with `VIP_REGIONS` in a guild object (meaning guilds can set bitrate to 384kbps).
> fix: voiceregion now fills correctly, removed VIP from regions.

- include/dpp/emoji.h
- include/dpp/isa/avx.h
- include/dpp/isa/avx2.h
- include/dpp/isa/avx512.h
- include/dpp/voicestate.h
- src/dpp/utility.cpp
- src/dpp/voicestate.cpp
This PR corrects some style issues that were not caught before. This PR also fixes the way variables were initalised in voicestate.
> style: corrected some left over style issues.

- docpages/building/osx.md
This PR changes the OSX page as it was missing pkg-config.
> docs: altered the OSX page

- include/dpp/discordvoiceclient.h
This PR changes `send_audio_type` in discordvoiceclient.h to be `satype_overlap_audio` if on windows. This should make issues like #978 hopefully appear less, if not at all.
> fix: changed default audio type for windows

- README.md
- docpages/INDEX.md
This PR corrects some punctuation with the section with Mac in the README.md, it also corrects some references in INDEX.md.
> docs: corrected punctuation and refs

- .github/workflows/ci.yml
This PR modifies the ci.yml file, making our unit tests now use `ctest -VV`. Since #1001 fixed the unit tests for Mac OS, we now unit test on the Mac OS runner.
The checklists do not apply to this PR.
> ci: unit tests now use ctest, macos now unit tests

- .github/workflows/ci.yml
This PR changes the ci.yml workflow to now use a matrix for MacOS. This also means we now have a self-hosted Mac runner (using Apple silicone) available!
> ci: Mac changes, self-hosted runner now available

- docpages/example_code/clearing_slashcommands.cpp
This PR makes some small changes to `clearing_slashcommands.cpp`, fixing up a spelling mistake. Thanks to @Mishura4 for spotting it 😅
> docs: corrected some issues in clearing_slashcommands.cpp

- .github/PULL_REQUEST_TEMPLATE/docs_change_template.md
- docpages/06_advanced_reference.md
- docpages/advanced_reference/docs-style-standards.md
- docpages/advanced_reference/docs_style_standards.md
This PR adds a docs convention, as discussed for a while now. If you have anything you want adding to this page, please feel free to say! I want to make sure we're catching most, if not everything, for docs here.
> docs: added a docs convention

- docpages/advanced_reference/docs-style-standards.md
This PR rewords some sections, now encouraging users to add images to their tutorials (to make it more user-friendly and to help us know they've tested their tutorial) and improving the wording for the testing section.
> docs: improved some sections for docs-style-standards

- docpages/03_installing.md
- docpages/install/install-brew.md
This PR adds a page to instruct people how to install D++ from homebrew.
> docs: added install page for brew

- docpages/style.css
The recent doxygen-awesome-css changes changed the colour of warnings and notes. I have rectified it and it is back to how it looked previously.
> docs: fixed colour scheme after recent doxygen changes

- .vscode/settings.json
- include/dpp/event_router.h
- include/dpp/exception.h
- include/dpp/sync.h
- src/dpp/cluster.cpp
- src/dpp/cluster/user.cpp
- src/dpp/commandhandler.cpp
- src/dpp/discordclient.cpp
- src/dpp/discordvoiceclient.cpp
- src/dpp/dns.cpp
- src/dpp/emoji.cpp
- src/dpp/etf.cpp
- src/dpp/guild.cpp
- src/dpp/message.cpp
- src/dpp/scheduled_event.cpp
- src/dpp/slashcommand.cpp
- src/dpp/sslclient.cpp
- src/dpp/webhook.cpp
This lets users check what type of exception by `exception.code()` instead of having to rely on string comparison of `exception.what()`. This is a non-breaking change as the previous functionality still exists alongside the old style constructors for anyone who is directly instantiating their own dpp exceptions in their bot (not sure why they would be, though).
Note the huge enum `exception_error_code` in exception.h. This will need to be maintained periodically by us as Discord add new errors. It can also be used with `get_error()` of a callback and matched against `get_error().code`.
> feat: add error codes to exceptions

- include/dpp/dispatcher.h
- src/dpp/events/ready.cpp
This PR adds the guilds array and a count of the array to the ready_t event, [as Discord provides an array of unavailable guilds on the ready event](https://discord.com/developers/docs/topics/gateway-events#ready-ready-event-fields). This means people can now get the amount of guilds a bot is in from the ready_t event.
> feat: added guilds array and count to ready_t

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
This PR makes `iteration_interval` in `discordvoiceclient.cpp` changeable, allowing people to use a different interval if they wish. Closes #1009.
> feat: Made iteration_interval changeable.

- docpages/example_code/setting_status2.cpp
- docpages/example_programs/misc/setting_status.md
This PR changes the setting_status page to use the feature added from #1038. I've also made the page move away from using the cache.
> docs: made the setting_status page use the latest ready_t feature

- src/dpp/slashcommand.cpp
Basically all examples of using `dpp::command_option` invoke undefined behavior Let's look at its typical usage example from the docs:
```cpp
dpp::slashcommand newcommand("blep", "Send a random adorable animal photo", bot.me.id);
newcommand.add_option(
dpp::command_option(dpp::co_string, "animal", "The type of animal", true)
);
```
The problem here is that `dpp::command_option::command_option` does not initialize a boolean field called `focused`. And then inside `add_option` the implicitly-defined copy constructor is called. This constructor, among other things, copies that `focused` field, but since it was never initialized, we get UB.
This PR ensures that `focused` is initialized in `dpp::command_option::command_option` with `false`.
> fix: use of uninitialized value in command_option copy ctor

- include/dpp/utility.h
- src/dpp/commandhandler.cpp
- src/dpp/utility.cpp
This PR solves the following problems:
- `dpp::utf8substr` is just broken: `dpp::utf8substr("abcdefg", 2, 2)` returns `"cdef"`. Probably unnoticed due to a very limited variety of usage scenarios.
- `dpp::utf8substr` and `dpp::utf8len` claim to have a specific result (empty string or zero, respectively) if the supplied string is not a valid UTF-8 sequence. In reality though, not only do they not verify if the string is valid UTF-8, they actually invoke UB for some inputs (e.g. `dpp::utf8len("\xC0\xC0")`) due to reading past the end of the string.
- The implementations of these functions are convoluted (use of `goto`, defining lots of variables in one line etc.).
- They only work with `std::string`s and not `std::string_view`s. In particular, `dp::utf8substr` returns a new `std::string`, …
> refactor: fix and improve utf8 utilities

- src/dpp/sslclient.cpp
Changes:
- Ensure that `SSL_CTX` is freed with `SSL_CTX_free` by using `std::unique_ptr` with custom deleter. Previously was leaking.
- Ensure that `SSL` is freed with `SSL_free` in `ssl_client::cleanup()`. Previously was leaking.
- Remove useless `try-catch`. If it failed to allocate, you have nothing to deallocate. The assignment doesn't even happen in this case, an exception is thrown when evaluating the right side.
> fix: properly free ssl session and ssl context

- src/dpp/sslclient.cpp
As correctly noticed by @braindigitalis, #1049 introduced an unnecessary `SSL_free` call. This PR removes it.
> fix: remove unnecessary SSL_free

- .github/workflows/ci.yml
This PR makes the `linux-with-unit-test` and `linux-no-unit-tests` one section now, reducing the size of the `ci.yml` file.
The checklist does not apply here.
> CI: unit-test and non unit-test jobs are now merged into one

- src/dpp/utility.cpp
During conversion from cmyk to rgb, blue value was calculated with m (magenta) instead of k (black)
> fix: cmyk calculations - blue value calculations

- .cspell.json
- docpages/install/install-windows-vs-zip.md
- docpages/make_a_bot/windows_vs.md
> docs: improve windows VS tutorials

- include/dpp/cluster.h
- include/dpp/cluster_coro_calls.h
- include/dpp/cluster_sync_calls.h
- src/dpp/cluster/channel.cpp
- src/dpp/cluster_coro_calls.cpp
- src/dpp/cluster_sync_calls.cpp
This PR adds the ability to set the status of a voice channel.
> feat: Added the ability to set voice channel statuses

- include/dpp/cluster.h
- include/dpp/cluster_coro_calls.h
- include/dpp/cluster_sync_calls.h
- src/dpp/cluster/guild_member.cpp
- src/dpp/cluster_coro_calls.cpp
- src/dpp/cluster_sync_calls.cpp
I've added dpp::cluster::guild_member_timeout_remove, dpp::cluster::guild_member_timeout_remove_sync and dpp::cluster::co_guild_member_timeout_remove and added documentation for them.
> Added dpp::cluster::guild_member_timeout_remove and its sync/coro versions

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR fixes labeler from failing CIs due to the update that was made which broke configuration files.
The checklist does not apply here.
> ci: labeler no longer fails

- include/dpp/message.h
- src/dpp/message.cpp
Added methods to extract expiration and issued timestamps from url
```c++
dpp::embed test{};
test.set_title("Test for file")
.add_field("filename", fileAttachment.filename)
.add_field("description", fileAttachment.description)
.add_field("url", fileAttachment.url)
.add_field("proxy_url", fileAttachment.proxy_url)
.add_field("Expiration timestamp", std::to_string(fileAttachment.get_expire_time()))
.add_field("issuing timestamp", std::to_string(fileAttachment.get_issued_time()));
```
> feat: Added expire and issued timestamps in attachment

- src/dpp/httpsclient.cpp
For some reason Blizzard's API doesn't send "OK" with "HTTP/1.1 200"
For some reason D++ REALLY wants there to be a 3rd thing separated by spaces there despite not using it ever
No more.
> fix: it's going to be OK

- include/dpp/cluster.h
default `= utility::log_error()` was missing for `interaction_followup_create` and `guild_template_create`
> [fix] default callback parameters

- include/dpp/message.h
This allows the developer to use only one parameter if they only require to change the first parameter and leave the others as default. Altered comments.
Example:
`dpp::message a = dpp::message().set_allowed_mentions(true); // this allows them to parse users but leave everything else as false`
> [feat] alter set_allowed_mentions

- src/dpp/cluster/thread.cpp
Used get_active_threads as a template to properly implement threads_get_public_archived and threads_get_private_archived
> fix: Fixed getting archived threads

- include/dpp/discordclient.h
- src/dpp/discordclient.cpp
A disconnect does not need to be issued before switching voice channels. This new function allows you to change voice channels without disconnecting beforehand.
> Added change_voice_channel to discordclient

- src/dpp/discordevents.cpp
This PR fixes the `ts_not_null` unittest breaking on a non-UTC machine. It also fixes `set_ts_not_null`.
For more understanding, `mktime` returns a **local time**, not a UTC time. It's also not based off your BIOS time, as previously assumed in #1063, but rather the user-level time.
Fixes #1063
> fix: ts_not_null now works for all timezones

- include/dpp/message.h
- src/dpp/message.cpp
This PR adds an embed-only constructor to `dpp::message`. Since `message(snowflake channel_id, const embed& _embed)` exists, it seemed natural and useful to have a version without the channel id.
```c++
// this is probably the most common reply on my bot
event.reply(dpp::message{}.add_embed(embed));
// now you could just do this
event.reply(dpp::message{embed});
// or this with the implicit conversion
event.reply(embed);
```
> feat: add embed-only message ctor

- library/CMakeLists.txt
Build DPP statically causing linker errors with OpenSSL with undefined references
```
/usr/bin/ld: s3_lib.c:(.text+0x348): undefined reference to `OPENSSL_sk_pop_free'
/usr/bin/ld: s3_lib.c:(.text+0x35c): undefined reference to `CRYPTO_free'
/usr/bin/ld: s3_lib.c:(.text+0x377): undefined reference to `CRYPTO_clear_free'
/usr/bin/ld: s3_lib.c:(.text+0x38b): undefined reference to `CRYPTO_free'
/usr/bin/ld: s3_lib.c:(.text+0x39f): undefined reference to `CRYPTO_free'
/usr/bin/ld: s3_lib.c:(.text+0x3ab): undefined reference to `EVP_PKEY_free'
/usr/bin/ld: s3_lib.c:(.text+0x3b7): undefined reference to `EVP_PKEY_free'
/usr/bin/ld: s3_lib.c:(.text+0x3d3): undefined reference to `CRYPTO_free'
/usr/bin/ld: s3_lib.c:(.text+0x3e7): undefined reference to `CRYPTO_free'
/usr/bin/ld: …
```
> fix: correct wrong linking order to fix static build

- include/dpp/cache.h
The `this` keyword is evaluated to a pointer to an object of a given type so `sizeof(this)` returns the size of the pointer instead of the object so use `sizeof(*this)` instead.
> fix: get size of object instead of pointer

- src/dpp/httpsclient.cpp
Since `i` is the index, it should be less than the size of the vector but the `mimetypes.size() < i` condition does not check for `i` being the same as the size of the vector, which causes an out-of-bounds read in the right operand of the logical OR (`||`) operator which is `mimetypes[i].empty()`.
> fix: out-of-bounds read of MIME types

- include/dpp/cluster.h
- include/dpp/cluster_coro_calls.h
- include/dpp/cluster_sync_calls.h
- include/dpp/coro/coroutine.h
- include/dpp/discordevents.h
- include/dpp/discordvoiceclient.h
- include/dpp/emoji.h
- include/dpp/event_router.h
- include/dpp/guild.h
- include/dpp/httpsclient.h
- include/dpp/prune.h
- include/dpp/role.h
- include/dpp/scheduled_event.h
- include/dpp/sku.h
- include/dpp/sslclient.h
- include/dpp/utility.h
- src/dpp/cluster_coro_calls.cpp
- src/dpp/cluster_sync_calls.cpp
This PR fixes many missing/incorrect params for some functions.
This PR also adds the `message_edit_flags` coro and sync calls, as they were missing from the last PR.
> docs: fixed missing/incorrect params for many functions

- include/dpp/guild.h
- src/dpp/guild.cpp
…member is the guild owner.
Added a helper method so that checking if the member is the guild owner is easier.
- [✅] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [✅] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [✅] I tested that my change works before raising the PR.
- [✅] I have ensured that I did not break any existing API calls.
- [✅] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.
> feat: Added is_guild_owner for dpp::guild_member

- src/dpp/cluster.cpp
This PR no longer allows empty presences for `set_presence`. It will now give a warning.
> fix: empty presences will now warn

- include/dpp/restresults.h
- src/dpp/cluster/confirmation.cpp
- src/unittest/test.cpp
Example:
```json
{
"message": "Invalid Form Body",
"code": 50035,
"errors": {
"data": {
"poll": {
"_errors": [
{"code": "POLL_TYPE_QUESTION_ALLOWS_TEXT_ONLY", "message": "This poll type cannot include attachments, emoji or stickers with the question"}
]
}
}
}
}
```
Currently the code assumes a `_errors` object either at the first or second level, this one is at the third level, so it wouldn't parse. This PR fixes that and adds handling of errors without an array: `Error: 50035: Invalid Form Body - data.poll: This poll type cannot include attachments, emoji or stickers with the question (POLL_TYPE_QUESTION_ALLOWS_TEXT_ONLY)`
> fix: fix human_readable for good

- src/dpp/sslclient.cpp
Only set signals to Ignore on non-Linux of no signal-handler is in place. Also set the SA_RESTART flag to avoid operations returning EINTR.
> fix: Signal Handlers on Non-Windows Platforms in sslclient

- src/dpp/cluster/confirmation.cpp
- src/dpp/utility.cpp
adds a try/catch around log_error internals to catch malformed or incorrect error output such as null error jsons
> fix: error in logging with malformed json that doesnt fit the structure for an error

- .github/workflows/ci.yml
This PR removes the self-hosted mac runner that is run by myself. It's getting too much to run this whilst also trying to test personal projects (thanks new mac os update). I'll look to bring it back in summer if I can figure out how to move it from a VM to a jailed process.
> ci: Mac runner removal

- include/dpp/cluster_sync_calls.h
- include/dpp/json_interface.h
- include/dpp/nlohmann/json.hpp
- src/dpp/auditlog.cpp
- src/dpp/cluster.cpp
- src/dpp/cluster/appcommand.cpp
- src/dpp/cluster/channel.cpp
- src/dpp/cluster/confirmation.cpp
- src/dpp/cluster/dm.cpp
- src/dpp/cluster/guild.cpp
- src/dpp/cluster/guild_member.cpp
- src/dpp/cluster/message.cpp
- src/dpp/cluster/role.cpp
- src/dpp/cluster/template.cpp
- src/dpp/cluster/thread.cpp
- src/dpp/cluster/user.cpp
- src/dpp/cluster/webhook.cpp
- src/dpp/cluster_sync_calls.cpp
- src/dpp/discordclient.cpp
- src/dpp/discordevents.cpp
- src/dpp/discordvoiceclient.cpp
- src/dpp/guild.cpp
- src/dpp/integration.cpp
- src/dpp/message.cpp
- src/dpp/role.cpp
- src/unittest/test.cpp
- src/unittest/test.h
> FIX: QOL: non fatal utf8 handling.

- docpages/example_code/autocomplete.cpp
Updated autocomplete tutorial to bypass recent command_type error with automatic conversion of c-style strings to booleans instead of to std::strings, with the hope that this code should now work out of the box for new developers.
The c-style string arguments near the ends of lines 53-56 are now explicitly converted to std::string before being converted implicitly to command_type.
> Updated autocomplete tutorial

- src/dpp/sslclient.cpp
change poll() to ::poll() to make it explicit we are referring to the C poll function outside our namespace.
> FIX: poll conflicting with dpp::poll

- include/dpp/message.h
This PR corrects the documentation for `set_allow_multiselect` as it had the same documentation as `set_duration`.
> docs: set_allow_multiselect is now correctly documented

- docpages/make_a_bot/token.md
This PR alters the wording in the Token page to tell users that they only need the `bot` scope, whilst also stating that they can look at the discord resource if they wish to see what might be applicable for them. I've seen an increase in users believing they need more than just the `bot` and `application.commands` scope, so I thought we should make it absolutely clear that they do not.
Whilst @braindigitalis and I discussed that technically it's currently correct saying they should also tick the `application.commands` scope, I still don't believe we should lead users to believe that they need the `application.commands` scope as Discord will silently include it regardless.
> docs: changed wording of token page

- include/dpp/entitlement.h
- src/dpp/cluster/entitlement.cpp
- src/dpp/entitlement.cpp
Adds missing fields from the docs and no longer assumes guild and user are both `owner_id`
> QoL fix: Enhance the entitlement stuff with data from the actual api docs now there are some

- include/dpp/coro/async.h
- include/dpp/coro/coroutine.h
- include/dpp/coro/task.h
Pretty useful when working with templates (for example, [this code I wrote](https://github.com/BowDown097/dpp-command-handler/blob/master/dpp-command-handler/commandfunction.h), where I had to reproduce this with a false_type/true_type struct). Similar conveniences are part of quite a few STL template types too, namely std::function which I'd say is pretty similar.
> Add result_type member type to dpp::task

- Dockerfile
Updated the Docker base DPP image to 24.04 and pinned it to a hash. [Here](https://hub.docker.com/layers/library/ubuntu/noble/images/sha256-c279a739b31ead4ebc3e9ce04937eb8b612799b52c26133eb3b4a056d08c31a6?context=explore) is a list of known vulnerabilities with 24.04 (although all of them have some vulnerabilities). Additionally removed the noninteractive line, since as of 23.04 it is patched (see [here](https://github.com/moby/moby/issues/4032) for the 10-year long papertrail!).
> Update Docker image to Ubuntu 24.04 LTS

- include/dpp/cluster.h
- include/dpp/cluster_coro_calls.h
- include/dpp/cluster_sync_calls.h
- src/dpp/cluster/entitlement.cpp
- src/dpp/cluster_coro_calls.cpp
- src/dpp/cluster_sync_calls.cpp
This PR adds the functionality to consume entitlements. This is not tested as I can not test entitlements.
> feat: Added consuming an entitlement

- include/dpp/entitlement.h
These enums didnt exist when the draft API was documented. Now they do, so they're added.
> feat: add missing entitlement type enum values

- include/dpp/appcommand.h
- include/dpp/message.h
- src/dpp/message.cpp
Adds the premium upsell button: https://discord.com/developers/docs/change-log#premium-apps-new-premium-button-style-deep-linking-url-schemes
> feat: new premium upsell button style

- include/dpp/bignum.h
- include/dpp/dpp.h
- src/dpp/bignum.cpp
- src/dpp/cluster/channel.cpp
- src/unittest/test.cpp
- src/unittest/test.h
Officially, the Discord documentation says that permission values can be any arbitrary number of digits. At time of writing there are only 50 bits of permissions, but this is set to grow larger and potentially past 64 bits. They will continue to send this data as a huge single integer at that point, because this is obviously sensible. **/s**
dpp::bignumber uses OpenSSL BN_* under the hood, as we include openssl anyway for HTTPS.
> feat: big number implementation, for future use in permissions bitfields

- include/dpp/message.h
- src/dpp/message.cpp
This makes the methods more flexible with types of input, most notably with string_views themselves so the user doesn't have to create a temporary std::string.
> Use string_view for message object ctors + setters

- src/dpp/cluster.cpp
This PR adds warnings for some events (guild member events and presence update) if the user does not have the specific intent required.
As these events do not fire from Discord if the intent wasn't specified, I could not use the `set_warning_callback` feature.
This is to try and inform users about what went wrong and how they can fix it, to try be more user friendly as D++ is currently silent about it (see [link a](https://discord.com/channels/825407338755653642/825411707521728512/1235314587868594309) and [link b](https://discord.com/channels/825407338755653642/825411707521728512/1250187664632840293)).
> feat: added warnings for certain events that require an intent

- .cspell.json
- README.md
- docpages/03_installing.md
- docpages/install/install-void-xbps.md
Added installation documentation for Void XBPS package manager
> Add XBPS docs

- include/dpp/dispatcher.h
- src/dpp/discordvoiceclient.cpp
- src/unittest/test.cpp
> fix: add packets_left count

- CMakeLists.txt
- include/dpp/dispatcher.h
- src/dpp/discordvoiceclient.cpp
- src/dpp/dispatcher.cpp
Unable to test voice because of broken unit test for voice send. 
Replaced std::basic_string with std::vector
Fix for [issue 1129](https://github.com/brainboxdotcc/DPP/issues/1129)
> fix: compilation on clang-19

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
This PR attempts to speed up the action runners by allowing them to use mold and also changing the concurrency to 3 instead of 2 (github action runners were updated to 4 cores a while ago).
The checklist does not apply here.
> ci: allow runners to use mold, increased concurrency to 4

- include/dpp/cluster.h
- include/dpp/cluster_coro_calls.h
- include/dpp/cluster_sync_calls.h
- include/dpp/misc-enum.h
- src/dpp/cluster/user.cpp
- src/dpp/cluster_coro_calls.cpp
- src/dpp/cluster_sync_calls.cpp
This PR adds the ability to add banners to bots. I have also removed the limit imposed on avatars and banners as it seems the 256kb limit isn't true.
> feat: banners can now be uploaded to bots

- src/unittest/test.cpp
- src/unittest/test.h
Fixes the ban set/unset/get unit tests to be properly dependent upon each other's callbacks (callback hell, yay) and also to use the IDs of valid users which should never be on a unit test server:
* MEE6
* Dyno
* MidJourney Bot
These 3 will remain valid for the forseeable future. using deleted user ids for bans is not a good idea, they eventually get purged and the side effects of adding bans for them is not doucmented behaviour.
> fix(test): fix ban unit tests to be dependent upon each other

- .github/workflows/ci.yml
This PR changes our OSX runner to have `clang++14` and `clang++15` jobs, instead of only `clang++14`. This PR also fixes the `clang++14` job, where it was actually `clang++15`.
The `clang++15` job is using Xcode 15.3 to ensure that `std::format` is tested (as versions below don't have `std::format`), however, it should be noted that we **NEED** to enforce checks for `std::format` features to prevent Xcode 15.2 and lower versions breaking, otherwise we will be heavily breaking OSX support.
> ci: Added a clang++15 osx job, fixed clang++14 job.

- docpages/example_code/editing_message_after_click.cpp
- docpages/example_code/editing_message_after_click2.cpp
- docpages/example_programs/interactions_and_components/components-menu.md
- docpages/example_programs/interactions_and_components/components/editing_message_after_click.md
This PR adds a page to show people how to edit messages from a button click (using stuff like `dpp::ir_deferred_update_message`, etc).
> docs: added a page for editing messages from a button click

- docpages/install/install-void-xbps.md
Remove the manually compiling with coroutine support section due to [package](https://github.com/void-linux/void-packages/commit/ca76d8ce914a9cc23321f9ed86d1435e3675b07a) being default compiled with coroutine support enabled
> docs: Remove XBPS coroutine section

- .github/workflows/ci.yml
This PR adds more clang jobs as #1201 showed that jobs can now run on `ubuntu24.04`. This PR also adds `clang16` for OSX as Xcode16 is available in beta.
> ci: added clang16-18 jobs for Linux, added clang16 for OSX

- src/dpp/discordevents.cpp
yet another soundboard event that isnt documented that bots recieve. Discord, you need to document or silence this nonsense, there are about 6 soundboard events now!
> fix(qol): shut up soundboard events

- include/dpp/user.h
- src/dpp/cluster/user.cpp
This PR adds a file size limit to avatars and banners as Discord seemed to silently introduce an avatar file limit (either that or it's always been there and it wasn't properly working the other day).
> feat: Added file size limit to avatars and banners

- include/dpp/cluster.h
- include/dpp/queues.h
- src/dpp/cluster.cpp
- src/dpp/queues.cpp
This PR changes the default request timeout to be 20 seconds. This PR also adds a function to `dpp::cluster` to allow users to change the timeout length if they wish.
> feat: timeout is now 20 seconds. Users can now change the timeout length

- include/dpp/cluster.h
- include/dpp/cluster_coro_calls.h
- include/dpp/cluster_sync_calls.h
- src/dpp/cluster/emoji.cpp
- src/dpp/cluster_coro_calls.cpp
- src/dpp/cluster_sync_calls.cpp
This PR adds support for application emojis.
> feat: Added support for application emojis

- include/dpp/httpsclient.h
- include/dpp/sslclient.h
- include/dpp/wsclient.h
- src/dpp/sslclient.cpp
- src/dpp/wsclient.cpp
This PR aims to make sslclient.cpp and wsclient.cpp more readable, making it easier to maintain. There are also a couple of extra improvements (moving from `#define` to `constexpr` for example).
> refactor: readability changes to sslclient and wsclient

- docpages/03_installing.md
- docpages/install/install-gentoo-portage.md
I'm one of the Gentoo maintainers for D++, so I decided to make a page on how to install it on Gentoo.
The tutorial explains how to enable GURU, how to install D++ using portage, how to enable voice and coro support, and finally how to build a bot using G++, as I noticed is the case with all other installation guides.
> docs: create Gentoo installation tutorial

- docpages/install/install-xmake.md
In xmake, init doesn't (anymore?) exist, the new command for creating projects is create
> docs: Change init to create

- docpages/example_code/commandhandler.cpp
Change incorrect comment in example code.
`omit for guild command` -> `omit for global command`
> fix: incorrect comment

- src/dpp/httpsclient.cpp
Fixes the "try using 1.0 instead" issue, I believe
> fix: fix requests fizzling if the response doesn't contain Content-Length

- include/dpp/export.h
- include/dpp/socket.h
This PR improves compatiblity with other projects that DPP is included into.
`#include <dpp/win32_safe_warnings.h>` is to prevent dll-interface warnings while compiling the main application.
`#ifndef SOCKET` is used to prevent possible incompatiblities with projects that already handle that case (such as network libraries). This way the socket will still be defined but only if it wasnt earlier.
> fix: Improve compatiblity with socket

- include/dpp/coro/awaitable.h
Added missing include _optional_ to awaitable.h.
Required for line 140.
> fix: Added missing include to awaitable.h

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
- Implements the new required XChaCha20 voice encryption for sending and receiving voice audio
> feat: XChaCha20 voice encryption

- src/dpp/discordvoiceclient.cpp
- src/dpp/guild.cpp
- src/dpp/httpsclient.cpp
This PR introduces `AEAD XChaCha20 Poly1305 (RTP Size)` as the encryption method for voice data.
`AEAD AES256-GCM (RTP Size)` will not be introduced in this PR as it is simply a suggestion (Discord declares it as a "preference", however, it's easier to just stick with `XChaCha20 Poly1305`) therefore, after discussions internally, we will stick with just `AEAD XChaCha20 Poly1305 (RTP Size)`
> feat: Change encryption to AEAD XChaCha20 Poly1305

- src/dpp/discordvoiceclient.cpp
Bumps audio websocket protocol from v4 to v8. Required going forward from November 18th.
> bump audio version to v8 from v4

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
> feat: receive_sequence for v8 voice gateway

- docpages/example_code/embeds.cpp
Remove not required intent from code example.
Add cout logger as we have it in other examples
> Docs: Fix embeds.cpp not required intent + add cout logger

- src/dpp/discordvoiceclient.cpp
- src/dpp/voice/enabled/enabled.h
- src/dpp/voice/enabled/handle_frame.cpp
- Allow downgrade/upgrade from/to dave on user join/leave
- Stage channel also working correctly
- Removed unnecessary calling ready handler on dave welcome event
> Feat/dave downgrade-upgrade

- include/dpp/cluster.h
- src/dpp/cluster.cpp
at this point it is draft pr to get feedback. i hope to test it tomorrow.
> Feat: Implementing named commands handlers for the cluster

- docpages/example_code/CMakeLists.txt
- include/dpp/commandhandler.h
This officially deprecates `dpp::commandhandler`. This PR should be merged after or alongside #1262.
Schedule for removal is undefined, there are many bots still using this, and removing it entirely would break too much stuff, but deprecating it allows us to wash our hands of it, stop updating it, and refuse to support it directly.
This also closes #1199 as obsolete
> refactor(deprecation): officially deprecate commandhandler

- src/dpp/thread.cpp
threads_get_public_archived crashes as it does not contain thread_metadata, which is assumed present in `thread::fill_from_json_impl`
Fixes #1269
> fix: crash in threads_get_public_archived

- library-vcpkg/CMakeLists.txt
fix vcpkg build to enable voice at all times. it brings in the deps it needs so does not need to check theyre there.
> fix: vcpkg is always built with voice

- include/dpp/discordvoiceclient.h
- src/dpp/discordvoiceclient.cpp
- src/dpp/voice/enabled/constructor.cpp
- src/dpp/voice/enabled/enabled.h
- src/dpp/voice/enabled/handle_frame.cpp
- src/dpp/voice/enabled/opus.cpp
- Fix dave user join/part implementation
- Tested `update_rachets` for more than 2 dave user (including bot) is joining/leaving the voice channel
- Tested Upgrade/Downgrade to/from dave when non-dave user join/leave the voice channel
> DAVE user join/part

- buildtools/classes/Generator/SyncGenerator.php
- include/dpp/cluster_sync_calls.h
- src/unittest/test.cpp
Deprecate sync calls, from now on they will be auto generated with DPP_DEPRECATED on them advising users to use coro.
This bypasses sync depreciation warnings in the unit tests by using the template directly instead. I don't want to touch this with a ten foot pole right now as this is a whole world of fragile callback hell. This can be addressed in the future maybe, but for now, this isnt directly end user facing code and isnt going to cause anyone any hassle.
> refactor(breaking): Deprecate sync calls

- src/dpp/dave/array_view.h
- src/dpp/dave/cipher_interface.cpp
- src/dpp/dave/cipher_interface.h
- src/dpp/dave/clock.h
- src/dpp/dave/codec_utils.cpp
- src/dpp/dave/codec_utils.h
- src/dpp/dave/cryptor_manager.h
- src/dpp/dave/decryptor.h
- src/dpp/dave/encryptor.cpp
- src/dpp/dave/encryptor.h
- src/dpp/dave/frame_processors.cpp
- src/dpp/dave/frame_processors.h
- src/dpp/dave/leb128.cpp
- src/dpp/dave/parameters.h
- src/dpp/dave/persisted_key_pair_generic.cpp
- src/dpp/dave/session.h
- src/dpp/voice/enabled/discover_ip.cpp
Properly adds comments to all libdave member variables. Some of these i'm not 100% sure of their purpose, but they have a comment now to get the process started.
This PR also backports some fixes from discord to libdave, I have picked out the important changes to apply to our implementation and left their stylistic changes and build script on the cutting room floor: https://github.com/discord/libdave/commit/6e5ffbc1cb4eef6be96e8115c4626be598b7e501#diff-f395bfd18d0d8d925834eef8a2732beff51c7bab0cb55b2901eacf3c01a39899R133
> docs: add docblock comments to all libdave class variables

- .clang-format
adds a clang-format file, exported from my clion settings that closely match the dpp code style. for discussion or inclusion.
> style: clang-format file, for discussion

- .github/dependabot.yml
- include/dpp/appcommand.h
- include/dpp/application.h
- include/dpp/integration.h
- include/dpp/message.h
- src/dpp/application.cpp
- src/dpp/message.cpp
- src/dpp/slashcommand.cpp
- src/userapptest/userapp.cpp
Finishes off support for user apps. Adds a few interaction methods, and fixes the interaction json parse to not die.
Fom original PR by Ray21
Documentation and examples to go into docs once this reaches master. For a working example see src/userapptest/userapp.cpp
> feat: add support for user apps

- include/dpp/discordvoiceclient.h
- src/dpp/dave/session.cpp
- src/dpp/dave/session.h
- src/dpp/voice/enabled/handle_frame.cpp
Dave is a total snowflake now.
> refactor: dont use strings and uint64_t in dave, use snowflake type

- src/dpp/slashcommand.cpp
This PR fixes #1310, fixing a crash when `contexts` is null (usually when a basic command is made).
Closes #1310
> fix: commands should no longer crash when no context is defined

- include/dpp/isa/neon.h
This PR fixes NEON not compiling.
Closes #1309
> fix: neon now compiles

- include/dpp/sslclient.h
ctime missing in sslclient breaks on void linux
> fix: missing ctime in sslclient.h breaks on void linux

- src/dpp/cluster.cpp
- src/dpp/cluster/guild_member.cpp
`cluster::guild_edit_member` accesses invalid memory in its callback if the guild_member object is deallocated before the `post_rest` makes a call to the callback. Capturing the object as copy fixes this issue.
`cluster::shutdown` does not clear the `next_timer` map which causes segfaults in `cluster::tick_timers` if the timers are not removed before shutdown. Clearing the map after all timers are deleted resolves this.
> fix: two segmentation faults in cluster::guild_edit_member and cluster::tick_timers/cluster::shutdown

- mlspp/CMakeLists.txt
backport from MLS++ as requested by @egorpugin
> fix namespace include in cmakelists for mlspp, backport of mls++ fix

- docpages/dl.dpp.dev/index.php
this is already live on dl.dpp.dev as there is no automatic deployment of this code.
> fix: dl.dpp.dev was not downloading rpms any more

- docpages/example_programs/misc/checking-member-permissions.md
- include/dpp/cluster.h
- include/dpp/cluster_sync_calls.h
- include/dpp/role.h
- src/unittest/test.cpp
- src/unittest/test.h
This is a **breaking change** for anyone using the comparison operators of the `dpp::role` class!
If two roles have the same position, their IDs are compared to find out which role is higher in the hierarchy. The higher the IDs are, the lower they are. Previously, only the position was compared.
Documentation: https://discord.com/developers/docs/topics/permissions#role-object-role-structure
> breaking: Updated dpp::role comparison operators to now consider role IDs

- .github/workflows/ci.yml
This PR is taken from #1334, fixing the OSX CI whilst the Socketengine PR is in draft. It removes the need for clang16.
The checklist does not apply for this PR.
> ci: OSX now only tests on clang15

- library/CMakeLists.txt
Building DPP statically with BUILD_VOICE_SUPPORT=OFF fails with undefined targets (related to HAVE_VOICE), so i put these targets in a if condition.
> fix BUILD_VOICE_SUPPORT=OFF static build

- src/dpp/voice/enabled/constructor.cpp
> fix: unitialized sent_stop_frames causing nasty pause/play playback confusion

- include/dpp/cluster.h
- include/dpp/zlibcontext.h
- src/dpp/cluster/timer.cpp
- src/dpp/socketengines/poll.cpp
- src/unittest/test.cpp
> fix: coro timers ez pz lemon squeezy

- include/dpp/socketengine.h
- src/dpp/socketengine.cpp
- src/dpp/socketengines/epoll.cpp
- src/dpp/socketengines/kqueue.cpp
- src/dpp/socketengines/poll.cpp
- src/dpp/wsclient.cpp
Adds functions to obtain statistical counters about the IO loop, for use in diagnostics and for bot info pages etc.
> feat: socket engine stats functions

- src/dpp/sslclient.cpp
- src/dpp/wsclient.cpp
We must set WANT_WRITE whenever we append to the write buffer of an ssl_client based object. This is the proper fix for the issue patched by @Neko-Life where voice wasn't sending via socketengine events. If the opcode 4 was not sent soon enough, then the connection would not succeed, this seems oddly temporal now. Setting WANT_WRITE in the ssl_client::write() function ensures all writes occur as soon as they possibly can.
> fix: make sure write events go out as soon as they can

- include/dpp/dispatcher.h
- src/dpp/dispatcher.cpp
The `message_create_t` type was missing direct coroutine function variations. So I have implemented functions and overloads for both `co_send()` and `co_reply()` functions. This PR improves code consistency and usability.
(Similar coroutine functions have already been implemented for `interaction_create_t` before, but not for `message_create_t`)
```cpp
#include <dpp/dpp.h>
#include <dpp/coro.h>
#include <coroutine>
#include <iostream>
const std::string BOT_TOKEN = "your bot token here";
int main() {
dpp::cluster bot(BOT_TOKEN, dpp::i_default_intents | dpp::i_message_content);
bot.on_log(dpp::utility::cout_logger());
/*
This example demonstrates the use of co_reply and co_send functions on the dpp::message_create_t event.
You can test them by sending !test1, !test2, !test3, and !test4 in a …
```
> Add coroutine support functions to message_create_t (co_send, co_reply)

- include/dpp/coro/awaitable.h
std::condition_variable is used in the awaitable.h file, so it should be included in it.
If you only include dpp::taks or similar header files, it will cause a linker error as it will not be able to link against std::condition_variabl, normally you would include dpp.h or other files that include a lot so It's not really noticeable.
> fix: Compile issue if task or awaitable is used by its own

- library/CMakeLists.txt
If DPP_CORO is configured to be true, the make_struct.php will *always* be run, even if not on UNIX or if PHP isn't found. This PR moves the relevant execute_process to where the other php files are run.
(and no, I'm not able to retarget or reopen the other PR)
> Don't always run php for DPP_CORO

- .github/workflows/release-documentation.yml
- SECURITY.md
- docpages/makedocs-gh.php
- sign.sh
> Tweaks and fixes to scripts and docs to support 10.1

- include/dpp/coro/awaitable.h
Fixes the following warning when compiling on MSVC:
```
dpp\include\dpp\coro/awaitable.h(686): warning C4245: 'argument': conversion from 'int' to 'const unsigned char', signed/unsigned mismatch
```
P.S. thanks to Discord user MacOS master.
> Fix C4245 warning on MSVC

- include/dpp/dispatcher.h
- src/dpp/events/message_reaction_add.cpp
Adds an user_id field to message_reaction_add_t.
When we get the callback from adding a reaction in a DM, the payload is as follows:
```
{
"t": "MESSAGE_REACTION_ADD",
"s": 4,
"op": 0,
"d": {
"user_id": "0000000000000000000",
"type": 0,
"message_id": "0000000000000000000",
"message_author_id": "0000000000000000000",
"emoji": {
"name": "âœ…",
"id": null
},
"channel_id": "0000000000000000",
"burst": false
}
}
```
This has no member or user information to fill the corresponding classes, making it impossible to get the user_id of the user that reacted.
Test code:
```
#include <cassert>
#include <memory>
#include <dpp/dpp.h>
#define TOKEN "ADD_BOT_TOKEN"
#define USER_ID ADD_USER_ID
class TestBot final {
public:
TestBot() {
bot_.on_ready([this](dpp::ready_t const& ready) { OnReady(ready); }); …
```
> Added user_id to message_reaction_add_t

- include/dpp/application.h
- include/dpp/integration.h
- mlspp/include/namespace.h
- src/dpp/application.cpp
- src/unittest/test.cpp
- src/unittest/test.h
* Fix bug with parsing of oauth2_install_params in current_application_get()
* Remove autogenerated mlspp namespace.h (it is already in gitignore)
* Add unit test for current_application_get()
* Change logger errors in unit tests to red prefix
Note: Instead of a map with always two std::optional in application::integration_types_config, the map now only contains keyed values for non-empty integration types instead of using std::optional. e.g. if your bot only has a guild invite, the map will only contain one value keyed to ait_guild_install. This is simpler and matches the way other things in dpp work.
> fix: oauth2_install_params in current_application_get() could not be parsed

- src/dpp/cluster.cpp
it is possible to call bot.start twice if you specify dpp::st_return
> fix: dont allow bot.start on a started cluster

- src/dpp/httpsclient.cpp
If the user tries to set multiple Content-Length, Host, or Connection HTTP headers, that conflict with those DPP sends, servers can exhibit non-deterministic behaviour. How they react is server specific, and can include closing the connection, returning the wrong page, etc.
We now filter these out.
Fixes #1382
> fix: deny user ability to set certain headers

- src/dpp/socketengine.cpp
Otherwise I see
`DPP-10.1.0/src/dpp/socketengine.cpp(26): fatal error C1083: Cannot open include file: 'sslclient.h': No such file or directory`
> Fix include dir.

- src/dpp/ssl_context.cpp
After raising this with Discord they have enabled support for TLS 1.3 on discord.media websocket endpoints. This now allows all of D++ to use TLS 1.3 as a minimum TLS version. 
Unit tests now pass with this set.
> security: bump minimum tls version for openssl to TLS 1.3

- CMakeLists.txt
clang 16 may bug out on macos if it is not explicitly provided
added a line to require c++17 before linking std::filesystem
> require c++17

- include/dpp/coro/awaitable.h
- include/dpp/coro/task.h
- include/dpp/coro/when_any.h
- include/dpp/http_server.h
- include/dpp/socket.h
- include/dpp/ssl_context.h
PR includes #1414 because I can't test otherwise
> fix(coro): fix when_any when an awaitable is already finished before co_await

- include/dpp/webhook.h
- src/dpp/cluster/webhook.cpp
This is a fix for #1416, adding a new property to the webhook struct to allow for custom avatar urls.
If an avatar_url is set, it will be used instead of the custom uploaded avatar.
> feat: Add avatar_url override for webhook struct, resolves #1416

- include/dpp/http_server_request.h
- src/dpp/http_server_request.cpp
Putting path and request_type to protected (making them available to retrieve in case of handle other request type than "POST")
> refactor: make method and path in http_server_request protected instead of private

- include/dpp/application.h
- src/dpp/application.cpp
https://discord.com/developers/docs/resources/application#application-object-application-structure
> feat: implement event webhook fields in dpp::application class

- src/dpp/application.cpp
- src/dpp/emoji.cpp
- src/dpp/integration.cpp
The previously used method `basic_json::to_string` adds quotation marks around the string when parsing. Replaced `basic_json::to_string` with `basic_json::get<std::string>`.
I noticed this issue in `dpp::application` and also adjusted it in `dpp::emoji` and `dpp::integration`.
> fix: json parsing issues with string arrays in dpp::application

- src/dpp/user.cpp
The endpoint for the avatar decoration seems to have changed: https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints.
Same for the json structure: https://discord.com/developers/docs/resources/user#user-object-user-structure.
fix #1418
> fix user::get_avatar_decoration_url() and parsing of the field

- include/dpp/discordclient.h
- include/dpp/discordvoiceclient.h
- src/dpp/discordclient.cpp
- src/dpp/events/voice_server_update.cpp
- src/dpp/events/voice_state_update.cpp
- src/dpp/voice/enabled/constructor.cpp
- src/dpp/voice/enabled/handle_frame.cpp
- src/dpp/voice/enabled/thread.cpp
- src/dpp/voice/stub/stubs.cpp
```txt
As instructed in Discord documentation, if resuming did not succeed,
the bot should attempt to reconnect from scratch.
```
It seems that a resume does not have to succeed after voice connection closes. See Discord documentation [Voice#Buffered Resume](https://discord.com/developers/docs/topics/voice-connections#buffered-resume)
> The resume may be unsuccessful if the voice gateway buffer for the session no longer contains a message that has been missed. In this case the session will be closed and you should then follow the [Connecting](https://discord.com/developers/docs/topics/voice-connections#connecting-to-voice) flow to reconnect.
In this change I made `discord_client` pass a callback into `voiceconn` for initiating the voice connection. `voiceconn` also passes a callback into …
> Attempt a full reconnection when a resume attempt failed.

- include/dpp/appcommand.h
- include/dpp/cluster.h
- include/dpp/dispatcher.h
- src/dpp/dispatcher.cpp
This is a refactoring and stability improvement for the coroutine helper functions on `message_create_t` and `interaction_create_t`.
Following a review discussion, all relevant `co_` helpers have been updated to use the modern "pass-by-value and move" C++ idiom. This change achieves two primary goals:
1. It fixes a critical dangling reference bug present in the original implementations that could lead to use-after-free errors and crashes.
2. It simplifies the API by replacing redundant `const&` and `&&` overloads with a single, more efficient signature.
To support this refactoring, `interaction_modal_response` was also made fully copyable and movable by implementing the Rule of 5.
> While the Rule of 0 would be preferred, this was not possible due to the class's explicitly declared …
> refactor(async): Modernize coroutine helpers and add follow_up functions

- include/dpp/compat.h
- include/dpp/socket.h
- src/dpp/socketengines/poll.cpp
- src/dpp/voice/enabled/discover_ip.cpp
I was working on personal project that included DPP and Asio, and DPP was defining `poll` that was clashing with asio's `asio::details::scheduler::poll` method, so I decided to remove it, I'm not sure how compat layers usually done in such project, so this is just my vision
> fix: get rid of poll macro

- include/dpp/cluster.h
- include/dpp/message.h
- include/dpp/permissions.h
- include/dpp/restresults.h
- include/dpp/role.h
- src/dpp/cluster/message.cpp
- src/dpp/message.cpp
- src/dpp/role.cpp
- src/unittest/test.cpp
This PR adds the new `PIN_MESSAGES` permission, and changes the get/set/unset pinned message endpoints to the new endpoints.
Because of the new endpoints, the `channel_get_pins` endpoint no longer returns the same data, meaning we now had to change this, causing a **breaking change** to make it conform to the new standard that Discord has set.
> breaking: rewrote channel_get_pins, added Pin Message permission, updated pin endpoints.

- src/dpp/cluster/channel.cpp
Sorry, I just pushed to the wrong branch.
fix ```cluster::channel_invites_get``` incorrect endpoint.
The third parameter (`minor`) is an empty str `""`, resulting in the incorrect API endpoint:
- **Actual:** `GET /api/v10/channels/{channel_id}`
- **Expected:** `GET /api/v10/channels/{channel_id}/invites`
> Fix: channel_invites_get incorrect endpoint
